### PR TITLE
Ticket/2776 title first feature card

### PR DESCRIPTION
**Pull request by erikscottmeyer**
ODE: ncigovcdode364.prod.acquia-sites.com

### CODE REVIEW

**Comment by claireblaustein** [comment]
It appears that the card isn't pulling the translated title/description when the page is translated. It is linking to the correct content.

Spanish report: http://ncigovcdode364.prod.acquia-sites.com/espanol/pets/claire-test-report
two column card links to: http://ncigovcdode364.prod.acquia-sites.com/espanol/pets/claire-test-article

(Both the card and the list item link to the same content - the list shows the updated title)
image

**Comment by KateMashkinaNIH** [comment]
According to AC **prop59** should have value   **titlefirst:card position** , but ODE shows `prop59 = titleFirstFeatureCard:card position`
P.S. Checked with Andrew, he stated that **titlefirst:card position** is the correct design
Screen Shot 2020-07-16 at 11 08 44 AM
ation value

**Comment by mworrest** [comment]
Line height on title first card too large on mobile.

**Comment by mworrest** [comment]
Line height on title first card too large on tablet.

**Comment by erikscottmeyer** [comment]
@claireblaustein I believe the content is translating correctly; the english and spanish versions of the test content had the same text in certain fields like browser title and list description; the Title First Feature Card uses the same field priority rules as the Feature Cards (it looks at title, browser title, etc. for content, and prioritizes them to determine what content to use).  I added ES in various fields in the test spanish page and they are showing up as expected on the SR. http://ncigovcdode364.prod.acquia-sites.com/espanol/pets/claire-test-report

**Comment by claireblaustein** [comment]
@erikscottmeyer thanks! I re-tested and it looks good to me.

**Pull request closed without merging**
