### PR TITLE
(#3398) Enable virus scanning for uploads

### PR DESCRIPTION
**Pull request by ramu-nih**
- Add clam AV to dockerfile
- Install and enable ClamAV drupal module
- Configure ClamAV module to point to executable
- Set outage action to allow
- Removed clamav settings from features yml file

Closes https://github.com/NCIOCPL/cgov-digital-platform/issues/3398

See https://github.com/NCIOCPL/cgov-digital-platform/pull/3476 for previous notes

### CODE REVIEW

**Comment by bryanpizzillo** [comment]
This appears to still need a behat or something test. @kate-mashkina maybe we can think about cypress for this now.

**Comment by kate-mashkina** [comment]
The cypress automated test had been created https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/pull/340
Regression tests passed on ODE528

**Review by blairlearn — APPROVED** [review]
Looks good to me, and verified to be working.

**Review by blairlearn — APPROVED** [review]
Scan is configured for executable mode, however Acquia doesn't support daemon mode. Regrettably, this will cause scans to run more slowly.

**Pull request merged**
