### PR TITLE
(#4236) Add additional library to home and landing page

### LINKED ISSUE #4236: Add CSS/JS to a single Home and Landing page
Implement the functionality of the combo box on the Cancer Types landing page, by adding CSS/JS to a single Home and Landing page without overloading other H&L pages.

Results of Spike: https://github.com/NCIOCPL/cgov-digital-platform/issues/4207

- We can create a new filed within our cgov_home_landing form display that gets populated with all libraries associated with the theme of the page (in this case, we would be targeting ncids_trans).

- In the fields storage config, add in the name of the [allowed_values_function](https://chromatichq.com/insights/dynamic-default-and-allowed-values-list-fields-drupal-8/) and implement that function within cgov_home_landing. This function will populate the drop down with all the libraries associated with the theme.

```
$themesvc = \Drupal::service('theme_handler');
$front_end_theme = $themesvc->getDefault();
$disco = \Drupal::service('library.discovery');
$libs = $disco->getLibrariesByExtension($front_end_theme);
```

- The "default" theme for a site is the front-end theme. It should never return the admin theme even if it runs in the admin. One thing is you can try this in `drush php`. That command opens up a PHP REPL prompt with all of Drupal available. It makes it easy to try out some of these types of things. (REPL is "Read, Evaluate, Print, and Loop" and not limited to PHP, you can find a REPL prompt for many languages.)

- We would need to create a new library that has the javascript and css that we would want to use on a specific page for the Cancer Types Landing Pages - [Drupal Documentation](https://www.drupal.org/node/2274843#define-library)

- Once a library is selected from the drop down, we would use [hook_page_attachments](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/function/hook_page_attachments/8.0.x) to attach the javascript that we selected to the correct page on our site.

### Tasks

- [x] Create the field - see[ Content Model](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Additional-Front-End-Library)
- [x] Create the entry point and Drupal library entry in the ncids_trans theme
- [x] Create a test YAML content scenario at /test/landing-page-library-test
  - Entry point created that is a js and css. JS does console.log and css makes something blue. @dev-rana-publicis  and @KateMashkinaNIH to work together to create acceptance tests

### PR DESCRIPTION
**Pull request by dev-rana-publicis**
Closes #4236
ODE: https://ncigovcdode705.prod.acquia-sites.com/

### CODE REVIEW

**Comment by KateMashkinaNIH** [comment]
Two issues observed 

1. There is a console error when editing a home and landing in the cms 
Screenshot 2024-02-21 at 11 01 50 AM

2. Warning message's link on Spanish page with additional library in the edit mode is purple ( where it should be yellow and it turns back to yellow once addl library is removed)
Screenshot 2024-02-21 at 11 09 06 AM

**Comment by adrianacastaneda** [comment]
Looks good to me!

**Comment by KateMashkinaNIH** [comment]
regression results ( all pass) - https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/actions/runs/8008398969/job/21874753812
https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/actions/runs/8008106467

issues mentioned above are fixed

**Review by sarinapadilla — APPROVED** [review]
Looks good!

**Review by bryanpizzillo — CHANGES_REQUESTED** [review]
Ok, we will do this as a 2 part review. 

Can we move the field storage and the attachments to cgov_core?
The field.field should still be in cgov_home_landing.

**Comment by KateMashkinaNIH** [comment]
This passes QA

**Pull request merged**
