### PR TITLE
(#2109) Blog Series show thumbnail field not working

### PR DESCRIPTION
**Pull request by daquinohd**
Added logic for thumb display in template

### CODE REVIEW

**Comment by daquinohd** [comment]
Ticket #2109 
### ODE: http://ncigovcdode219.prod.acquia-sites.com

**Comment by lburack** [comment]
@daquinohd @claireblaustein @VictoriaSunNIH – it appears that that no thumbnail image display option is now working, but the URLs are not working as expected — the blog series is not being included in the URL string for the post:

**Blog Series:** http://ncigovcdode219.prod.acquia-sites.com/test/cards/lbb-blog
**Blog Post:** http://ncigovcdode219.prod.acquia-sites.com/test/cards/2019/blog-post-2

**Comment by daquinohd** [comment]
@lburack - this is ready for testing again.

**Comment by lburack** [comment]
This is now working as expected. Passes IA review.

**Comment by daquinohd** [comment]
Combined into PR #2170; closing.

**Pull request closed without merging**
