### PR TITLE
(#4363) 3 Feature Card Row for MLP 

### LINKED ISSUE #4363: Allow 3 Feature Card Row paragraph to be added to Mini Landing Pages
## As a content editor, I want to be able to add a feature card row to my page, so that I can feature content.

* Required row heading
* Feature Card Style
* This will reuse the 3 Feature Card Row from Home & Landing pages
  * The image aspect ratio was updated to always be 16:9 per #4367 
* Optional View All button TABLED FOR LATER IMPLEMENTATION IN SEPARATE TICKET
  * View All Internal
    * Alt text
  * View All External
    * Alt text

### Technical Resources
- Content Model
  - Added to [Paragraph Types](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Paragraph-Types#ncids-mini-landing-page-components)
  - New [NCIDS Optional Heading 3 Feature Card Row](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Paragraph-Type-NCIDS-Optional-Heading-3-Feature-Card-Row) Paragraph
- [Comp](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=4504-13476&m=dev)
- Scenarios:
  - Create an `/about-cancer/understanding` page to match the Figma comps on the Priority MLP pages. This should link to `What is Cancer?`, `Cancer Statistics` and `Cancer Disparities`. 
  - On the "Chronicles and Adventures..." page, please create a 3 Feature Card Row with the heading, "Test Links", with an NCIDS Feature Card Internal, an NCIDS Feature Card External, and an NCIDS Feature Card Multimedia with the following respective links, "[About Cancer](https://www.cancer.gov/about-cancer)", "[Google](https://www.google.com/)", and "[Implementation Science Infographic](https://www.cancer.gov/research/implementation-science-infographic)"

DoR Tasks
 
- [x] Content Model Drafted
- [x]  Content Model Reviewed
  - [x]  Developer Review
  - [x]  IA Review
- [x]  Content Model Approved
  - [x]  Developer Approval
  - [x]  IA Approval
- [x]  Acceptance Criteria Drafted
  - [x]  Analytics Acceptance Criteria Drafted (As applicable)
- [x]  Scenarios created for YAML
- [ ]  Acceptance Criteria Reviewed
  - [ ]  Developer Review
  - [x]  IA Review
  - [ ] Analytics Review
- [ ]  Acceptance Criteria Approved
  - [ ]  Developer Approval
  - [x]  IA Approval
  - [ ] Analytics Review

DoD Tasks

- [ ]  Governance Drafted
- [ ]  PR Review (see PR for review and comments)
- [ ]  Client Review with Demo

### Acceptance Criteria

```gherkin
Scenario: A content editor adds an NCIDS 3 Feature Card Row to a Mini Landing Page with the NCIDS style
  Given a content editor is on the CMS
    And the content editor is creating or editing a Mini Landing Page
    And the Mini Landing Page has the NCIDS style
  When the content editor goes to the Contents section of the CMS page for the Mini Landing Page
  Then the content editor can choose from the dropdown to add an NCIDS 3 Feature Card Row to the Mini Landing Page
  When the NCIDS 3 Feature Card Row is added to the Mini Landing Page
  Then the content editor will see the Heading field
    And the Heading field is required
    And it is a text entry field
    And the tooltip says, "Displays above the row of cards. Used to concisely describe the featured content."
    And below the Heading field is the Feature Cards field
    And the Feature Cards field is optional
    And it allows the selection of the following types: NCIDS Feature Card Internal, NCIDS Feature Card External, NCIDS Feature Card Multimedia, and Raw HTML Content
    And an NCIDS Feature Card Internal will automatically be added to the NCIDS 3 Feature Card Row
    And the NCIDS Feature Card Internal will show the fields of that component (see Content Model)
    And at the bottom of the NCIDS 3 Feature Card Row paragraph there is a dropdown that allows the content editor to add other feature cards to the row
  When the content editor has three total cards in the NCIDS 3 Feature Card Row
  Then the dropdown button to add another feature card to the row will disappear
  When an NCIDS Feature Card Row has been added to a Mini Landing Page
  Then it will look exactly like the comps (see link above)
    And it will behave the same as the NCIDS 3 Feature Card Row and its feature cards as the component on the Home & Landing Pages
```

**Analytics**
```gherkin
Scenario: Analytics event for feature card clicks
  Given a user is on a Mini Landing Page
    And the Mini Landing Page uses the NCIDS style
    And the Mini Landing Page has a feature card
  When the user clicks on a feature card
  Then there will be an NCIDataLayer Other event
    And the event has the name "MLP:FeatureCard:LinkClick"
    And the event has the linkname "MLP:FeatureCard:LinkClick"
    And the event has the following data:
    | key | value |
    | location | Body |
    | pageType           | This will return the value of the page type and should match the dcterms.type meta data tag on the page.                                                                                                                 |
    | pageTemplate       | This will return the value of the page template and should match the cgdp.template meta data tag on the page.        
    | pageRows | This will return the total number of rows on the page overall |
    | pageRowIndex | This will return the index of the row number on the page of the click |
    | pageRowCols | This will return the total number of columns in the row of the click |
    | pageRowColIndex | This will return the index of the column in the row of the click |
    | containerItems | This will return the number of feature cards in the feature card row or the container holding the feature card |
    | containerItemIndex | This will return the index of the feature card clicked in the feature card row or the container holding the feature card |
    | componentType | Feature Card |
    | componentTheme | This will default to 'Light' |
    | componentVariant | This will return 'Default' |
    | linkText | This returns the displayed feature card title |
    | title | This returns the displayed feature card title |
    | linkType | This will return the value 'Card' |
    | linkArea | This will return 'Not Defined' |
    | totalLinks | Default will return 1 |
    | linkPosition | Default will return 1 |
```

### Notes

---

### PR DESCRIPTION
**Pull request by bryanpizzillo**
ODE: https://ncigovcdode790.prod.acquia-sites.com/
Closes #4363

### CODE REVIEW

**Comment by welshja** [comment]
Analytics looking good on the ODE for Feature Card Row on MLPs.

**Comment by monika-jaeger** [comment]
Looks good from my end for design!

**Comment by blilianyu** [comment]
Looks great and the new image crops work well!

**Review by andyvanavery31 — APPROVED** [review]
Passes Product Review

**Review by olitharp-nci — APPROVED** [review]

**Review by dev-rana-publicis — APPROVED** [review]

**Pull request merged**
