### PR TITLE
(#2733) Implemented mobile infographic field

### PR DESCRIPTION
**Pull request by bryanpnih**
- Add the mobile optimized infographic field. Change the desktop label.
- add inline infographic options, view modes and templates

Co-authored-by: Arce, Paul (NIH/NCI) [C] <arcepaul@users.noreply.github.com>

### CODE REVIEW

**Comment by claireblaustein** [comment]
Testing accessibility:

Large - English and Spanish - Pulling long desc as caption

```
<figcaption><div class="caption-container no-resize">
              SPANISH Accessible text long desc
          </div>
```

Medium - English and Spanish - not pulling field at all

**Comment by blilianyu** [comment]
We need to put in a new requirement for Infographic pages to have picture element at 768 as well. 

Screen Shot 2020-04-21 at 10 52 27 AM

**Comment by blilianyu** [comment]
Promo image field should be removed and have override crops
Screen Shot 2020-04-21 at 2 43 13 PM

**Comment by meglake** [comment]
> Promo image field should be removed and have override crops
> Screen Shot 2020-04-21 at 2 43 13 PM
@blilianyu  this isn't part of the 2733 story, the promo image filed should be left as is for this sprint.

**Comment by meglake** [comment]
> We need to put in a new requirement for Infographic pages to have picture element at 768 as well.
> 
> Screen Shot 2020-04-21 at 10 52 27 AM

@blilianyu, this is captured in our story's acceptance criteria. @arcepaul and @adriancofie here is the acceptance criteria pulled from the story:
**Infographic Page**
Scenario: View infographic page on a mobile device – has mobile optimized version
Given The user is using a device with a screen at 768px or smaller
  And The user is viewing an infographic page
  And The infographic has a mobile version 
Then The mobile version is displayed
  And the infographic appears at 100% of column width

**Comment by meglake** [comment]
In addition to the issues reported by @claireblaustein and @blilianyu I am not seeing the tool tips specified in the acceptance criteria for Uploads:

- Desktop tool tip- "Desktop version of the infographic."
- Mobile tool tip - "Mobile version of the infographic. Will appear on devices with a screen size of 768px or smaller."

**Comment by claireblaustein** [comment]
Tests complete - still seeing some issues:

- Tooltips are missing from upload fields
- Link of View/Print should be to file in new tab, not page (first time I tried went to the infographic page, second test started just opened article in a new tab... )
- Mobile breakpoint is happening at 627px - should be 768px
- with large template, CMS side is showing image at less than 100% (front end is fine) 
- Translated pages have same issues as english 
- long desc is missing from all inline embeds 


Also something I noticed - the file uploads are getting numbers appended to them, even though this is the first time I've uploaded in this build. Wanted to flag. 

image

**Comment by meglake** [comment]
@arcepaul @adriancofie - Completed testing and seeing a few remaining minor issues:
1. Tooltips are missing from upload fields. Desktop: "Desktop version of the infographic." Mobile: "Mobile version of the infographic. Will appear on devices with a screen size of 768px or smaller."
2. When embedding an infographic on a page using the large template, the CMS side is showing the infographic at less than 100% in the WYSIWYG. Front end is fine. (Not sure if this is fixable or if it's just the limits of the WYSIWYG)
3. File uploads are getting numbers appended to them, even though this is the first time I've uploaded in this build. (Claire first reported this and I'm seeing it too - not sure if this is an issue or not though).

**Comment by claireblaustein** [comment]
@arcepaul When a page doesn't have a left navigation, the grey bar under the large infographic extends beyond the borders of the image.

image

**Comment by blilianyu** [comment]
> @arcepaul When a page doesn't have a left navigation, the grey bar under the large infographic extends beyond the borders of the image.
> 
> image

All infographics should have a left nav so this is a non-issue.

**Comment by blilianyu** [comment]
Embedding an infographic on a page using the large template is showing at 100% in the WYSIWYG  now.

**Pull request merged**
