### PR TITLE
(#4486) Adds right padding to caption

### LINKED ISSUE #4486: Add Padding to Image & Video Caption on 2 Column Layout
### Issue Description
The padding-right on the captions for Images and Videos for 2-Column Layout on MLP NCIDS style are missing.

### What's the expected result?
- Padding should be applied to the right side of the caption with padding-right 16px (token 2)

### What's the actual result?
- There is no padding on the right.

### Additional details / screenshot
- Image
- Image

### Related Tickets
* Original Issue #4414

### PR DESCRIPTION
**Pull request by dlescarbeau**
Closes #4486

### CODE REVIEW

**Comment by blilianyu** [comment]
Updates look great!!

**Review by andyvanavery31 — APPROVED** [review]
Passes product review.

**Comment by KateMashkinaNIH** [comment]
visual regression passed https://github.com/NCIOCPL/cgov-digital-platform-acceptance-tests/actions/runs/11805360292

**Review by bryanpizzillo — COMMENTED** [review]
This looks fine, but will need to be rebased & fixed up after the NCIDS update most likely.

**Review by olitharp-nci — APPROVED** [review]

**Pull request merged**
