### PR TITLE
Ticket/1314 Video Form Updates and Date Display Bug

### LINKED ISSUE #1314: Video Form Display, ToolTips and Field Updates, Front End Display
### **Form Display:**
- [x]  **Name** should be moved to display below Site Section and Pretty URL

- [x]  **Meta-Description** Field 
  - [x] Add this field below Card Title, above List Description

- [x] **Related Resources**:
  * Add this field beneath date display mode.  

- [x] **Search Engine Restrictions**
  - [x] Add this field beneath Related Resources  
  - [x] Make this field required
  - [x] This should default to "Include in Search"

### **Field Updates:**
- [x] **Pretty URL** needs updated tooltip: Used as the last segment of the URL. Leave blank if page is the designated landing page in the site section. Do not include slash (/). All lowercase, with no spaces; use hyphens to separate words. 

- [x]  **Short Title** field needs to be updated tooltip to: A short version of the title. Suggest max 45 characters including spaces. [Displays in: Lists, CTHP Research Cards, social media sharing]

- [x] **Card Title** needs updated tooltip: A shortened version of the title, for use in cards and lists. If left blank, short title will display instead.

- [x]  **Browser Title** field needs updated tooltip to: A shortened version of the title. Site name is automatically appended (Browser Title – National Cancer Institute) [Displays in: internal and external search results, browser tabs. SEO best practice: max 42 characters including spaces]

- [x]  **Meta-Description** Field 
  - [x] Add the tooltip: Succinct description of the page content. [Displays in: internal and external search results. SEO best practice: Max 320 characters, most important information should be in the first 150 characters]

- [ ]  **List Description** field:
  - [ ] Add Tooltip: 2-3 sentence description of the page content. [Displays in: Lists on Home/Landing, Mini Landing, and Cancer Research pages. If left blank, meta description will display instead] 

- [x]  **Feature Card Description** field: 
  - [x] Update tooltip: Concise description for the page. Suggest max 75 characters. [Displays in: feature cards] 

- [ ] ~~**Lead Image** tooltip update: Displays in top right position on the page. Used for lists, cards, and social media sharing, unless Promotional Image is selected.~~

- [ ] ~~**Promotional Image** tooltip update:  Overrides Lead Image for promotional use cases (lists, cards, social media sharing)~~

- [x] **Posted Date** field needs tooltip update: Date the content was posted.
- [x] **Reviewed Date** field needs tooltip update: Date that the content was last reviewed by subject matter expert. 
- [x] **Updated Date** field needs tooltip update: : Date that changes were published to body text of page. 
- [ ]  **Date Display Mode** field:
  - [ ] This should be a multi-select checkbox.
  - [ ] Also make sure to include the front-end styling to display dates on video pages according to these rules:
    * When more than one date is selected in Date Display Mode - use the most recent of the dates selected. Display the label of that date, and that date. If only one is selected, show the label and the date. If nothing is selected, no date displays
- [x] Tooltip update:  Select which date to display. [Displays on page, beneath the body text]

- [x] **Search Engine Restrictions** field needs to add tooltip: Indicate how a page should be handled by internal (sitewide search) and external (Google) search engines.

- [x]  **Body** field: 
  * This needs to not have the dropdown to select the WYSIWYG, and instead be set to Full.

- [x]  **Caption** field: 
  * This needs to not have the dropdown to select the WYSIWYG, and instead be set to Simple

## Make sure that Form Display matches the following order:
How the fields should display on the form
* Language Dropdown
* Site Sections
* Pretty URL
* Name
* Short Title
* Browser Title
* Card Title
* Meta Description
* List Description
* Feature Card Description
* YouTube Video URL
* Body
* Caption
* Posted Date
* Updated Date
* Reviewed Date
* Date Display Mode
* Related Resources
* Search Engine Restrictions

### PR DESCRIPTION
**Pull request by adriancofie**
Closes #1314 

* Adds Related Resources, Meta Description, and S.E Restriction fields
* Update Field Order / Tooltips
* Limit text formats for WYSIWYG 
* Fix date display bug

### CODE REVIEW

**Comment by adriancofie** [comment]
on http://ncigovcdode97.prod.acquia-sites.com/

**Comment by lburack** [comment]
Hi @adriancofie –a couple of issues:
- the Name (Title) tooltip isn't correct. Please update to remove 'Displays on: Lists;'. The tooltip should read as follows:
> Please update to read: Unique and descriptive Title (H1 heading) for the page. [SEO best practice: 75 characters including spaces] 
- List Description isn't correct. Need to add '2-3 sentence description of the page content.' at the beginning. The tooltip should read as follows:
> 2-3 sentence description of the page content. [Displays in: Lists on Home/Landing, Mini Landing, and Cancer Research pages. If left blank, meta description will display instead]
- ALSO, the URL is not working as expected — it's not picking up the site section or appending the pretty URL I entered.

**Comment by VictoriaSunNIH** [comment]
@adriancofie , @lburack - the part about the URL not being correct, is it a similar issue to https://github.com/NCIOCPL/cgov-digital-platform/issues/1362 for infographics?

**Comment by adriancofie** [comment]
Updated. Same ODE: http://ncigovcdode97.prod.acquia-sites.com/

**Comment by adriancofie** [comment]
@VictoriaSunNIH Yep, same. Left a comment on #1362. I've fixed the issue in this PR.

**Comment by lburack** [comment]
The URL functionality appears to be working now as expected. 
The List Description tooltip is correct. Name tooltip is now missing, but I believe this field doesn't have tooltips across content types, so this is good to go. Marking as Passed IA Review.

Thanks!

**Comment by adriancofie** [comment]
@lburack  Thanks! Also, name tool tip IS showing for me on the ODE? /  I added logic specifically to get it to appear. Will follow up offthread.

@bryanpizzillo  can you merge?

**Comment by VictoriaSunNIH** [comment]
@adriancofie - @lburack , @BrendanBeltzNIH and I had discussed this at length and we agreed to not programmatically add tooltips to media as it's not a vital thing.  I forgot to remove that update from this video ticket though.

**Comment by adriancofie** [comment]
Talked to Brendan and I don't necessarily agree with the programmatic / dynamic argument since as-is currently ANY tool tip change will require a release. We shouldn't be making those types of changes directly in production, so they require a full release.

Not a sword worth dying on so removing from this PR for now.

**Comment by bryanpizzillo** [comment]
@adriancofie Can you please clean up this PR so that it is 1 commit with #1314? It also looks like something else went wrong since I see commits from previous PRs.

**Pull request merged**
