### PR TITLE
Added config for Blog Series pretty url alias

### PR DESCRIPTION
**Pull request by daquinohd**

### CODE REVIEW

**Comment by daquinohd** [comment]
New ODE: http://ncigovcdode44.prod.acquia-sites.com/

**Comment by VictoriaSunNIH** [comment]
@lburack - this looks good to me!  your turn!

**Comment by lburack** [comment]
The URL of my blog series looks to be working correctly.

FWIW, the page title (h1) is not displaying on the blog series. It has an <h2> of "Blog Posts" but that shouldn't be there. http://ncigovcdode44.prod.acquia-sites.com/about-cancer/lbb-blog

@daquinohd @VictoriaSunNIH

**Comment by VictoriaSunNIH** [comment]
Marking this as passed!

**Pull request merged**
