### PR TITLE
Allow periods for Pretty URLs.

### LINKED ISSUE #1304: We should allow periods in pretty URL
PDF files on cancer.gov have a pretty URL ending with .pdf 

We need to make sure the pretty URL field allows the period character. 

The largest application for this would be in Files, but may also occur in other pretty URLs.  

In testing #1284, I had a pretty URL that ended in .pdf. When I tried to save, I got this error: The Pretty URL field only accepts letters, numbers, and dashes.  The site section browser does appear when I try to add a file

### LINKED ISSUE #1582: Update pathauto to allow periods to appear in URLs
We allow periods to appear in pretty URLs now - but when the URL is saved, pathauto generates the URLs with underscores in place of the periods.

We need to look into a method to allow periods to actually appear in the pretty URL instead of being replaced.

### PR DESCRIPTION
**Pull request by adriancofie**
Closes #1304 
Closes #1582
Allows periods in pretty URL fields.

ODE: ncigovcdode115.prod.acquia-sites.com

### CODE REVIEW

**Comment by VictoriaSunNIH** [comment]
This ODE: http://ncigovcdode96.prod.acquia-sites.com

**Comment by VictoriaSunNIH** [comment]
@adriancofie - the pretty URL allows me to put periods in it, but the actual URL in the browser changes the periods to dashes.  The URL should retain the periods that are in the pretty URL.

**Comment by adriancofie** [comment]
Updating the path auto config referenced in (#1582) in this PR as well.

**Comment by adriancofie** [comment]
ODE: ncigovcdode115.prod.acquia-sites.com

**Comment by VictoriaSunNIH** [comment]
@lburack - this is looking good to me - file was added with periods in the pretty URL, and it retained the pretty URL.

**Comment by lburack** [comment]
I was able to add a file with a pretty URL ending in .pdf. The link worked as expected. I also tested that I can use linkit to link to the PDF and the URL appears as expected.
Passes IA Review!

**Pull request merged**
