### PR TITLE
Ticket/778 image crop

### LINKED ISSUE #471: Enlarge Field on Image Content Type
This story is to create the file [Enlarge](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Images#enlarge) and attach it to the Image content type.

This field will be a checkbox with the label "Enlarge" that, if selected, will add an Enlarge button to an image which allows the user to view the full original image. If it is not checked, there will be no Enlarge button on the image. The checkbox should default to unchecked.

### LINKED ISSUE #778: Implement image media type cropping tool
## System Wide Crops
The following are all of the crops that are available to be configured within the system. Not every image type needs to use these crops, but they should be reused whenever the same aspect ratio/sizes are needed.

### Freeform
* Name: Freeform
* Machine Name: freeform
* Description: This is a freeform crop to be used by lead or contextual images.
* Aspect Ratio: N/A
* Soft Limits
   * Width: 970
   * Height: N/A

### Thumbnail
* Name: Thumbnail
* Machine Name: thumbnail
* Description: A crop used for lists.
* Aspect Ratio: 4:3
* Soft Limits
   * Width: 194
   * Height: 146

### 4x3
* Name: 4x3
* Machine Name: 4x3
* Description: This is the crop that is used for feature cards, social media, and lists.
* Aspect Ratio: 4:3
* Soft Limits
   * Width: 324
   * Height: 243

### 3x4
* Name: 3x4
* Machine Name: 3x4
* Description: For future use.
* Aspect Ratio: 3:4
* Soft Limits
   * Width: 243
   * Height: 324

### 1x1
* Name: 1x1
* Machine Name: 1x1
* Description: For future use.
* Aspect Ratio: 1x1
* Soft Limits
   * Width: N/A (?)
   * Height: N/A (?)

### 16x9
* Name: 16x9
* Machine Name: 16x9
* Description: This is used on CTHP and Multimedia cards.
* Aspect Ratio: 16x9
* Soft Limits
   * Width: 577
   * Height: 324

### 9x16
* Name: 9x16
* Machine Name: 9x16
* Description: For future use.
* Aspect Ratio: 9x16
* Soft Limits
   * Width: 324
   * Height: 577

* Crops will be created manually, with the user determining the focal point
  * Manual cropping will be constrained by default aspect rations

### LINKED ISSUE #780: Create Image Media Type Display Modes
Create display modes to associate an image with its display, e.g., use panoramic for multimedia.

## Image Styles
These are the definitions of the various image "uses" throughout the site. You can produce multiple images from a single crop and use them in different ways across the site. Currently our crops match pretty closely to not only the aspect ratio but size. However, for example if we want the 4x3 crop that is used for social media to be 800x600, and the feature card image to be 324x243, we could configure that in the styles.

### Article
* Name: Article
* Machine Name: cgov_article
* Effects:
   * Manual Crop using _Freeform_ crop
   * Scale width 970

### Display Enlarge
* Name: Display Enlarge
* Machine Name: cgov_display_enlarge
* Effects:
   * Manual Crop using _Freeform_ crop

### Thumbnail
Unfortunately Drupal ships with its own thumbnail generator for every image. We want to use it in the editing interfaces, so we can't remove it. Its name is "Crop thumbnail" and has an additional "Thumbnail (100x100)" -- please do not confuse them with our thumbnail image.
* Name: Thumbnail
* Machine Name: cgov_thumbnail
* Effects:
   * Manual Crop using _Thumbnail_ crop
   * Scale 194x146

### Featured
* Name: Featured
* Machine Name: cgov_featured
* Effects:
   * Manual Crop using _4x3_ crop
   * Scale 324x243

### Social Media
* Name: Social Media
* Machine Name: cgov_social_media
 * Effects:
   * Manual Crop using _4x3_ crop

### Panoramic
* Name: Panoramic
* Machine Name: cgov_panoramic
* Effects:
   * Manual Crop using _16x9_ crop
   * Scale 577x324Image Styles

### PR DESCRIPTION
**Pull request by bryanpnih**
* Added the image cropping tool to cgov_image
  * Added crops and image styles
* Added image override fields to cgov_image
* Added in Enlarge functionality
* Updated Templates, View and view hooks to support crops and overrides
Closes #780 
Closes #778 
Closes #471

### CODE REVIEW

**Comment by VictoriaSunNIH** [comment]
@lburack here is the ODE for this: http://ncigovcdode38.prod.acquia-sites.com

**Comment by VictoriaSunNIH** [comment]
@bryanpizzillo - Alt text should not be required, and if it is not provided, we should output ""

**Comment by VictoriaSunNIH** [comment]
@bryanpizzillo  - noticing that credit appears on teh front-end of articles, even when no credit has been put in for the image

http://ncigovcdode38.prod.acquia-sites.com/news-events/press-releases

**Comment by bryanpizzillo** [comment]
@VictoriaSunNIH and @lburack 
* The Credit Issue and the alt text should be fixed.
* The permissions were missing from our users file on the ODE. So it was not a "real" issue. (You would have just had to grant the permission to the users)
* There is an outstanding issue I noticed that should be backlogged so this can get out. Empty content in the WYSIWYG will draw an empty caption box. (This is because, technically, there is content in the WYSIWYG even if it is empty lines)

**Comment by lburack** [comment]
@bryanpizzillo @VictoriaSunNIH 
- Credit no longer appears if that field is left blank, BUT 
- there needs to be a space after the colon (e.g., Credit: iStock). This is what I'm seeing on the front-end now:

screen shot 2019-03-04 at 6 48 57 pm

**Comment by VictoriaSunNIH** [comment]
@bryanpizzillo  - Agreed with @lburack  - this is looking good except for the spacing issue with Credit.

**Comment by VictoriaSunNIH** [comment]
@bryanpizzillo - spacing looks good!  Putting the label on it now.

**Comment by VictoriaSunNIH** [comment]
@bryanpizzillo - a few more items:
* All upload fields should be restricted to 10 MB max for upload sizes
* Please add recommended sizes as tooltips to the override fields:

**Comment by VictoriaSunNIH** [comment]
@bryanpizzillo - this looks good to me now.  I've entered a bug for the alt text separately, so I think we're good to go!

**Pull request merged**
