### PR TITLE
(#1091) Add og:image tag logic.

### LINKED ISSUE #1091: Metadata: Implementation of og:image meta tag
## Description 

This ticket captures the implementation of the logic and functionality for the 
og:image meta tag

* og:image
  * Add an og:image tag to [Promotional Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#promotional-image)
     * If no promotional Image has been provided, the system will add og:image tag to [Lead Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#lead-image)

### PR DESCRIPTION
**Pull request by adriancofie**
Closes #1091 

Adds og:image meta tag.

ODE: http://ncigovcdode139.prod.acquia-sites.com/

### CODE REVIEW

**Comment by lburack** [comment]
Looks good on Articles, but this does not pass IA review because all the other content types were not updated as well. @adriancofie - please make sure to add og:image meta tag to the following content types:
- Article (done)
- Biography
- Blog Post
- Blog Series
- Cancer Center
- Cancer Type Home Page
- Cancer Research List Page
- Event
- Home/Landing
- Mini Landing Page
- Press Release
- Infographic
- File

**Comment by adriancofie** [comment]
@lburack The code I added applies to all content types and media with the promo or lead image field  so something else must be going on here.

Looking briefly it looks crops might not be getting created correctly for some YML content. If you resave an image (I tried Jennifers bio), it complains that the crops do not exist.

The business logic does not add the tag for items which don't have the social media crop or social override image.

By any chance were the images referenced all imported via YML? Can you try re-saving one of the images tested and see if you encounter the same behavior?

**Comment by VictoriaSunNIH** [comment]
@adriancofie - ok, looks like it was a YAML image content issue.  But now i'm seeing something else, when I try to go to the URL for the og:image, it leads to a page not found: http://ncigovcdode139.prod.acquia-sites.com/sites/default/files/styles/cgov_social_media/public/2019-05/sunnysun.JPG

Shouldn't I be able to see my image when I follow the link?

**Comment by adriancofie** [comment]
@VictoriaSunNIH  One minute, looking on the server to see if there's anything in the logs / weird with file permissions.

**Comment by VictoriaSunNIH** [comment]
@adriancofie , @lburack - per our conversation via slack, I now see the og:image on other content types, but there is a larger issue where the image can’t write to the filesystem on the ODE so I can't test the URL.  Leaving this ticket open for retesting once the other issue is fixed.

**Comment by adriancofie** [comment]
@VictoriaSunNIH can you re-try this? May need to clear your browser cache or use a different browser if the site doesn't come up.

**Comment by VictoriaSunNIH** [comment]
This is looking good for all content types - passes IA review!

**Pull request closed without merging**
