### PR TITLE
(#4190) Update acquia/blt-acsf to v1.1

### LINKED ISSUE #4190: Enabler: Update acquia/blt-acsf to v1.1
# Update the [blt-acsf](https://github.com/acquia/blt-acsf) package to v1.1.

This is a pre-requisite for updating BLT past the current 13.7.0.0.
 - blt-acsf 1.1 removes `cache_dir` variable (and directory creation) from the hook scripts.
 - blt 13.7.1.0 removes the `vendor/acquia/blt/scripts/blt/drush/cache.php` script which blt-acsf 1.0 calls.

> **ESTIMATE** TBD

### Resources:

- https://packagist.org/packages/acquia/blt-acsf
- https://github.com/acquia/blt-acsf/releases/tag/v1.1.0

### PR DESCRIPTION
**Pull request by blairlearn**
- Replace db-update/db-update.sh with the new version.
- Replace post-site-install/post-site-install.sh with the new version
- Move factory-hooks/post-install/z-cgov-post-install.php to
  post-site-install/z-cgov-post-site-install.sh and update boilerplate
  from post-site-install.sh.
- Delete post-install/post-install.php.  This was renamed to
  post-site-install/post-site-install.sh as noted in the acquia/blt repository's
  issue 4061.  It is no longer a documented hook.
- Update factory-hooks/db-update/z-cgov-post-update.sh to match
  factory-hooks/db-update/db-update.sh

Closes #4190

This code only executes on ACSF.
Standard regression testing is requested.

### CODE REVIEW

**Comment by bryanpizzillo** [comment]
@blairlearn you need to rebase this off the Drupal 10 upgrade branch. Not because that is going first, but because I probably updated to acquia/blt-acsf already.

**Comment by KateMashkinaNIH** [comment]
QA passes code on test-acsf

**Comment by blairlearn** [comment]
Rebased to include 0867ed128618e3a78298e7d87fbac5c897fe99f3 (Twitter/X logo)

**Comment by blairlearn** [comment]
Rebase to include 7951b0485941362dcae1a592a5bc4466ec400210 and 7951b0485941362dcae1a592a5bc4466ec400210  (SAML configuration changes)

**Review by bryanpizzillo — APPROVED** [review]
Style-wise they look good.

**Pull request merged**
