### PR TITLE
(#2922) Issue with event start and end times.

### LINKED ISSUE #2922: Events - End Time Shall Not Be Allowed to be Earlier Than Start Time
### Issue description
*Description of the issue*
For events (seen in DCEG) we can select earlier end time than start time but when we download the event in the outlook, the start time is always the earlier time entered. So outlook always picks up the earlier time entered in the CMS and relates it to the Start Time. To fix this issue, the CMS will be changed so that a content editor cannot put an end time that occurs prior to the start time.

### Steps to reproduce the issue

1.  Create an event content type on DCEG
2. Select date as the system date
3. Select End Time earlier than Start Time (For example, Start Time 3pm and End Time 6am).
4. Publish the event content type
5. View at the front end and the time will appear as 3:00pm-6:00am
6. For adding to the Outlook Calendar click the "Add to Outlook Calendar" link

### What's the expected result?
- If a user in the CMS puts an end time that occurs earlier than the start time, then the user shall be given an error and not allowed to post the event.

### What's the actual result?
- The front end time appears as 3:00pm-6:00am and not in sync with the Outlook Calendar

### Acceptance Criteria

```gherkin
Scenario: A content editor tries to add an event with a start time later than end time in English
  Given a content editor is logged into the CMS
    And the content editor is creating a new event in English
  When the user enters a start time of 3pm on June 1st 2024
    And the user enters an end time of 6am on June 1st 2024
    And the user clicks the "Save" button
  Then the system will display an error message "Start date and time must begin before event ends. Please select a start date and time that begins prior to the event end date and time."
    And the content editor cannot save the content item
```

```gherkin
Scenario: A content editor tries to add an event with a start time later than end time in Spanish
  Given a user is logged into the CMS
    And the content editor is creating a new event in Spanish
  When the user enters a start time of 3pm on June 1st 2024
    And the user enters an end time of 6am June 1st 2024
    And the user clicks the "Save" button
  Then the system will display an error message "La fecha y la hora de inicio deben ser anteriores a la finalización del evento. Seleccione una fecha y una hora de inicio anteriores a la finalización del evento."
    And the content editor cannot save the content item
```

### Additional details / screenshot

image

### Related Tickets
* Originally captured in #1669 which was closed due to this ticket having more information.

### LINKED ISSUE #2992: Console error appears on loading PDQ summaries
### Issue description

Getting console error on loading PDQ summaries. Test url: https://www.cancer.gov/types/childhood-cancers/late-effects-pdq

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  
2. 
3. 

### What's the expected result?
-

### What's the actual result?
-

### Additional details / screenshot

image

### Related Tickets
* Issue #9999
* Issue #9999

### PR DESCRIPTION
**Pull request by navsunka**
Closes #2922

### CODE REVIEW

**Comment by alinai** [comment]
Looks good on ODE682. 
@sarinapadilla , @andyvanavery31 will be entering new tickets for pre-existing issues reported on #2922. 
cc: @KateMashkinaNIH , @santwuma

**Review by bryanpizzillo — CHANGES_REQUESTED** [review]
Can you do this so it is not only through the UI. The problem with a form alter is that the validations do not fire when saving through the API and calling validate() on the content type. 

Funny enough, the Drupal.org example is this use case. https://www.drupal.org/docs/drupal-apis/entity-api/entity-validation-api/defining-constraints-validations-on-entities-andor-fields#s-example

**Review by bryanpizzillo — COMMENTED** [review]
This is good for QA. I will wait until it passes.

**Review by bryanpizzillo — COMMENTED** [review]
This is good for QA. I will wait until it passes.

**Comment by alinai** [comment]
@navsunka ,  when the error message is displayed, I noticed in the first round of testing that the "Start Date and Time" was getting focus. Now in the 2nd round of testing, I am noticing that the End Date and Time is getting the focus. Per @sarinapadilla , If the error message is referring to start date and time, the Event Start Date & Time fields should be getting the error focus."
image

**Comment by alinai** [comment]
Looks good on ODE682. cc: @KateMashkinaNIH , @navsunka , @santwuma , @sarinapadilla

**Review by bryanpizzillo — APPROVED** [review]

**Pull request merged**
