### PR TITLE
Implement Lists both Dynamic and Managed

### LINKED ISSUE #526: Create Reusable View Block
We need to create a reusable view block that can be inserted on landing pages and mini landing pages.  

See https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Home-&-Landing-Page#view-block

### LINKED ISSUE #699: Mini Landing Page List – No Image Display Option
This ticket is to implement a list card block on the mini landing page. This is because not all mini landing page content have images to displays in a thumbnail card. We need this list option so we can display only a title and description.

This mini landing page list should include the following templates @bryanpizzillo:
* List Header | Item Title | Item Description
* Item Title | Item Description (no header)
* Item Title only (no header; no description)

We also need a list with thumbnail image, which has been built as part of #461. Just documenting here for documentation sake.

mini-landing-list-templates

### LINKED ISSUE #814: Convert Thumbnail Row Paragraph to List
## Description 

This is the backend story for #699 is to convert the thumbnail row paragraph (`cgov_thumbnail_row`) to a `List` (`cgov_list`) paragraph.

Changes:
* Change `cgov_thumbnail_row` to `cgov_list`
   * move it to `cgov_list` module
   * Change label to be `List`
* Add dropdown for list styling
   * In a perfect world this would be driven by the available display modes for the paragraph types that are allowed
* Change the unlimited card row (`field_unlimited_row_cards`) to list items (`field_list_items`)
   * Allow:
      * cgov_external_link
      * cgov_internal_link
      * (media will be a future requirement)
* Replace header field (`field_container_heading`) with `field_list_title`
   * Keep the settings the same, except the Label -- this should be `List Title`
* Update Home/Landing and Mini-Landing to remove thumbnail row and replace it with List
* Add display modes for all the list views
* Make templates

### Title Only
Note: this list style has a bullet (see example links). These should **not** be h3s, but just an anchor.
   * https://www.cancer.gov/policies
   * https://www.cancer.gov/types/brain/clinical-trials
### Title and Description
The title should be an h3. See #979 for additional markup changes
   * https://www.cancer.gov/about-cancer/treatment/clinical-trials/nci-supported
      * See Testing and Screening Trials
   * http://www.devbox/test/mini-landing/li-title-desc
### Title, Description and Image 
The title should be an h3. See #979 for additional markup changes
   * **Landing Page**
      * https://www.cancer.gov/research
         * See Video Stories item
      * http://www.devbox/test/mini-landing/li-title-desc-img
   * **Non-landingpage** 
      * https://www.cancer.gov/about-cancer/managing-care

**For lists on a Mini Landing Pages, we are getting rid of all lists with dates!!**

### LINKED ISSUE #979: Make list styles work
For our lists in Drupal, we want to use the HTML markup for lists, but with the front-end look and feel (for the most part*) of our current thumbnail cards
- Examples for HTML markup:
  - https://www.cancer.gov/about-cancer/managing-care
  - https://www.cancer.gov/about-nci/leadership/director/blog-posts
- Examples for look and feel:
  - https://www.cancer.gov/about-cancer/coping 
  - https://www.cancer.gov/grants-training

*The hover state should only change when a user hovers over the title or the image (and not the description)

**Additional Requirements:**
- When a list has a List Title, that should be an h2
- Each list item title should be an h3 

@lburack and @VictoriaSunNIH to discuss getting rid of lists with dates b/c we only have two of these on the site and one is questionable. Will update this ticket after meeting with Lynn.

### PR DESCRIPTION
**Pull request by bryanpnih**
Includes:
* Implement managed Lists for Home & Mini Landing Pages (Closes #814 & Closes #699)
* Implement Dynamic Lists (Closes #526)
  * Actually implements News & Events block for press releases (Untested #299)
  * Actually implements News & Events archive block for press releases (Untested #297)
* Stying for Managed and Dynamic Lists (Closes #979)
ODE: http://ncigovcdode63.prod.acquia-sites.com/AH_VIEW

### CODE REVIEW

**Comment by VictoriaSunNIH** [comment]
@bryanpizzillo - some things I've seen so far:
- On a home and landing page, when I select list with images, and one of the links does not have an image, it should show a blank space (and not left align)
- Alignment of the list title does not align to the guide card and title spacing
- Main Contents should not appear above Recent Press Releases

**Comment by lburack** [comment]
Does not pass IA review. Created #1147 for display issues on mini landing page.

**Comment by arcepaul** [comment]
@VictoriaSunNIH 
The issues that @lburack described in Bug #1147 should be addressed with this latest update and I am looking at the issues you raised in your comment.
1) **On a home and landing page, when I select list with images, and one of the links does not have an image, it should show a blank space (and not left align)** 
  >> investigating this now
2) **Alignment of the list title does not align to the guide card and title spacing**
  >> This should be taken care of with latest update
3) **Main Contents should not appear above Recent Press Releases**
 >> Is this just because "Main Contents" was added as an optional label?

**Comment by VictoriaSunNIH** [comment]
@arcepaul  Alignment of the list title does not align to the guide card and title spacing - this is still an issue!

**Comment by lburack** [comment]
@arcepaul, as discussed the list _without_ image option needs to have the same h3 font size as the list _with_ image (20px or 1.25em)

Also, the compact list is pulling the page title, but it should pull the short title. I've created #1235 for this.

**Comment by lburack** [comment]
It looks to me like lists now pass IA review. Huzzah!

**Pull request merged**
