### PR TITLE
(#3104) Remove image deletion for image managers when an image is pub…

### PR DESCRIPTION
**Pull request by suryatheja-muppalla**
…lished

Closes : #3104 

Removed the permissions for the image manager to delete the image or contextual image if it was published.

### CODE REVIEW

**Comment by adriancofie** [comment]
@bryanpizzillo should there be a test case for this?

**Comment by adriancofie** [comment]
Adding needs req's label, see :
https://github.com/NCIOCPL/cgov-digital-platform/issues/3104#issuecomment-891885428
https://github.com/NCIOCPL/cgov-digital-platform/issues/3104#issuecomment-891979630

**Comment by bryanpizzillo** [comment]
> @bryanpizzillo should there be a test case for this?

Yes. For Node's deletion, the test is https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/modules/custom/cgov_core/tests/src/Kernel/WorkflowTest.php#L114

**Comment by bryanpizzillo** [comment]
Also, the implementation for Node's delete is https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/modules/custom/cgov_core/cgov_core.module#L98

(It checks the revision history for being published.)

**Comment by ramu-nih** [comment]
This is replaced by #3502

**Pull request closed without merging**
