### PR TITLE
Preview link doesn't work for Content in Editing (in moderated view)

### LINKED ISSUE #834: Preview link doesn't work for Content in Editing (in moderated view)
When looking at moderated content in the content overview view, the link to view content that is in editing mode is broken (and displays an "unexpected error" page).

### PR DESCRIPTION
**Pull request by bgnih**
Fixes #834

### CODE REVIEW

**Comment by VictoriaSunNIH** [comment]
@bgnih - is there an ODE to review on?  Please post, thanks!

**Comment by bryanpizzillo** [comment]
ODE - http://ncigovcdode55.prod.acquia-sites.com/

**Comment by lburack** [comment]
This is working for me. @VictoriaSunNIH let me know if you have any issues, but I think this can be marked as Passed IA Review!

**Comment by VictoriaSunNIH** [comment]
Looks good to me too!

**Pull request merged**
