### PR TITLE
Add field_caption and alt text to infographics.

### LINKED ISSUE #2703: Add alt text field to the infographic
## As a content creator, I want to associate alt text with an infographic, so a user can see it when the infographic is in any context

> **ESTIMATE**  NEEDS ESTIMATE

#### Add Field

```gherkin
Scenario: add alt text field to desktop infographic upload
Given that the creator is on an infographic media type
	And there is an upload field titled "Infographic – Desktop Version" 
	And the creator uses the "Choose File" button to select a file
	And the file is attached to the media type
Then the alternative text field will appear
	And it will be a plain text field
	And it will not be required
	And tooltip text appears underneath that reads "Short description of the image used by screen readers and displayed when the image is not loaded. This is important for accessibility."
```

```gherkin
Scenario: Hide alt text field on mobile infographic upload
Given that the creator is on an infographic media type
	And there is an upload field titled "Infographic – Mobile Version"
	And the creator uses the "Choose File" button to select a file
	And the file is attached to the media type
Then no alternative text field will appear
```

#### View Page Source - Desktop 

```gherkin
Scenario: User wants to view alt text of inline infographic - has text
Given the user is viewing the desktop version infographic on a page at any template
	And the infographic has "Test alt text" in the Alt text field of the desktop file upload
When the user views the page source """alt text="Test alt text"" appears in the source code for the image
```

```gherkin
Scenario: User wants to view alt text of inline infographic - has text
Given the user is viewing the desktop version infographic on a page at any template
	And the infographic has no text in the Alternative text field of the desktop file upload
When  the user views the page source an empty alt text tag (alt text="") appears in the source code
```

#### View Page Source - Mobile 

```gherkin
Scenario: User wants to view alt text of inline infographic - has text
Given the user is viewing the mobile version of a infographic on a page
	And the infographic has "Test alt text" in the Alt text field of the desktop file upload
When the user views the page source """alt text="Test alt text"" appears in the source code for the image
```

```gherkin
Scenario: User wants to view alt text of inline infographic - has text
Given the user is viewing the mobile version of a infographic on a page
	And the infographic has no text in the Alternative text field of the desktop file upload
When  the user views the page source an empty alt text tag (alt text="") appears in the source code
```

#### View Page Source - Promo Image

```gherkin
Scenario: User wants to view alt text of promo image for infographic - has text
Given the user is viewing a list or card that links to the infographic
	And the infographic has "Test alt text" in the Alt text field of the desktop file upload
When the user views the page source """alt text="Test alt text"" appears in the source code for the image
```

```gherkin
Scenario: User wants to view alt text of promo image for infographic - has text
Given the user is viewing a list or card that links to the infographic
	And the infographic has no text in the Alternative text field of the desktop file upload
When  the user views the page source an empty alt text tag (alt text="") appears in the source code
```

### Resources

* Feature: https://tracker.nci.nih.gov/browse/CGOV-11460
* Mockups: https://publicis.invisionapp.com/share/CJW8VVAV87U
* Web Page: https://www.cancer.gov/research/areas/biology

### Notes

* Field will also need to be added to existing infographics - because it is not required, older infographics can be saved without adding alt text. HOWEVER, a cleanup effort should add alt text to infographics to ensure accessibility. 

---

### Prerequisites

*required dependency for identifying the problem, scope and then solution for this issue*

### Tasks

- [ ] Enable the built in alt text field for the desktop info graphic.
- [ ] Update the article_large article_medium and full templates
- [ ] Ensure there is a representative .YML content file.

### LINKED ISSUE #2765: Add caption to infographic
## As a content creator, I want to have the ability to add a caption to an infographic, so the user can get further context of the infographic.

> **ESTIMATE**  NEEDS ESTIMATE

#### Add Field	

```gherkin
Scenario: Add a caption to the infographic
  Given User is in an infographic media type 
  Then  A field titled "Caption" will appear in the CMS
  	And it will be below the field "Body" 
    And has a field name of "field_caption"
    And is a simple WYSIWYG
    And the field is optional
    And a tooltip appears under the field that reads "Enter image caption [Displays below image]"
 Then when user clicks "Save" on the media item, the caption is saved and added to the infographic media type
```

#### Display - In-Line

```gherkin
Scenario: View caption on an inline infographic
  Given that an infographic has text in the caption field
  When a user views a page with an infographic placed in-line
  Then the caption text appears in a grey box under the infographic
 	 And the "View and Print Infographic" button shows below the caption 
```
```gherkin
Background 
	Given that the language is set to "ES"
Scenario: View caption on an inline infographic on a Spanish page
  Given that a Spanish infographic has text in the caption field
  When a user views a page with an infographic placed in-line
  Then the caption text appears in a grey box under the infographic
  	And the "Ver y Imprimir Infografía" button shows below the caption
```

#### Display - Page

```gherkin
Scenario: View caption on an infographic page
  Given that an infographic has text in the caption field
  When a user views the infographic page
  Then the caption text appears in a grey box under the infographic
 	 And the "View and Print Infographic" button shows below the caption 
```

```gherkin
Background 
	Given that the language is set to "ES"
Scenario: View caption on a Spanish infographic page
  Given that a Spanish infographic has text in the caption field
  When a user views a Spanish infographic page
  Then the caption text appears in a grey box under the infographic
 	 And the "Ver y Imprimir Infografía" button shows below the caption
```

### Resources

* Feature: https://tracker.nci.nih.gov/browse/CGOV-11460
* Mockups: Full-width: https://publicis.invisionapp.com/share/CJW8VVAV87U#/408035405_Infographic_Full_Caption
40%: https://publicis.invisionapp.com/share/CJW8VVAV87U#/408035406_Infographic_40-_Caption
 
* Web Page: https://www.cancer.gov/research/areas/biology

### Notes

* existing infographic templates:

```media--cgov-infographic--full.html.twig
media--cgov-infographic--multimedia-card.html.html.twig
media--cgov-infographic--infographic-display-article-medium.html.twig
media--cgov-infographic--enitity-browser-selected-entity.html.twig
media--cgov-infographic--infographic-display-article-large.html.twig
media--cgov-infographic--infographic-display-article-medium.html.twig
```

---

### Prerequisites
#2733

### Tasks

- [ ] Add the caption field and export to config.
- [ ] Update the article_large, article_medium, and full display modes to enable the field.
- [ ] Update the article_large, article_medium, and full templates use caption
- [ ] Update the representative YAML content

### PR DESCRIPTION
**Pull request by adriancofie**
- Adds field_caption to the infographic CT and updates templates
- Enables the alt text for field_infographic, and adds logic for mobile
- Adds YAML content for infographic embeds

Closes #2703 
Closes #2765

### CODE REVIEW

**Comment by meglake** [comment]
@adriancofie  and @arcepaul  finished testing and this looks great! Only one minor thing I found missing:
- Caption field is missing tool tip "Enter image caption [Displays below image]"

@claireblaustein, I noticed that the alt text user story doesn't mention the infographic page. Are we planning to leave that page with just the long description and an empty alt tag? @arcepaul  any accessibility issues with this plan? 

Also I noticed that the medium template embeds in the WYSIWYG are going full width (CMS side), the last sprint they were showing at 40% as expected. However, the display is accurate on the front end for both the medium and the large template. Any idea why this is happening?

**Comment by adriancofie** [comment]
@claireblaustein @meglake  That's something that can be added quickly / we should include it with the story. I can push up the change once everyone has had a chance to test.

**Comment by kate-mashkina** [comment]
'view and print infographic' link should not be displayed on mobile breakpoint according to comps, but it is still there on YAML when resized (even after refreshing browser while on the same breakpoint)
Screen Shot 2020-05-08 at 11 45 54 AM

here is the comp https://publicis.invisionapp.com/share/CJW8VVAV87U#/screens/408035408

**Comment by meglake** [comment]
> 'view and print infographic' link should not be displayed on mobile breakpoint according to comps, but it is still there on YAML when resized (even after refreshing browser while on the same breakpoint)
> Screen Shot 2020-05-08 at 11 45 54 AM
> 
> here is the comp https://publicis.invisionapp.com/share/CJW8VVAV87U#/screens/408035408

Noting that this has been reported as a bug and will not be fixed within current sprint (sprint 2).

**Comment by meglake** [comment]
@adriancofie and @arcepaul - noting that I tested the latest updates on ODE and I'm seeing all issues resolved:

- Caption tool tip is in place
- Alt text is visible on infographic page when you inspect element
- I'm no longer seeing the medium template embed go full width in the WYSIWYG

Thank you!!

**Pull request merged**
