### PR TITLE
Bug/64 fix workflow

### PR DESCRIPTION
**Pull request by bkline**

### CODE REVIEW

**Comment by bkline** [comment]
@bryanpizzillo: The PR failed because RolesTest.php couldn't find the `content_author` role (and I assume would have had the same problem with other roles had it not given up with the first failure). Do we (a) comment out the role tests? (b) hoist the tests out of the `modules` section higher in the tree? (c) adopt some other solution?

I'm a little puzzled, to be honest, that the tests inside the `modules` section can't find things which are configured in the enclosing profile's `config`. So nesting things inside a hierarchy doesn't accomplish what it normally would, I assume. (In a normal scoping world, inner contexts can see things created by enclosing contexts, but not the other way 'round.)

**Comment by bkline** [comment]
I tried setting `protected $profile = 'cgov_site';` in the `RolesTest` class and adding `$this->setInstallProfile($this->profile);` in the `setUp()` method, but that didn't have any effect.

**Comment by bryanpizzillo** [comment]
@bkline Did you add any tests, or are you working on that as a separate item?

**Comment by bkline** [comment]
That's issue #106.

**Comment by bkline** [comment]
Thanks! And thanks for your help.

**Pull request merged**
