### PR TITLE
Ticket/dceg connect tickets

### PR DESCRIPTION
**Pull request by erikscottmeyer**

### CODE REVIEW

**Comment by alinai** [comment]
1. Magnifying glass is almost not visible in the Search box.

image

2. The logo text is blurred.

image

3. A white space appears on scrolling down from the top.

image

4. Font of text should be 18px (per comp)

image

5. "JOIN THE STUDY" button/link on the footer should be all uppercase per comp.

**Comment by alinai** [comment]
At mobile breakpoint, 
1) The images are not center aligned.
2) Horizontal scroll bar appears.

image

3) Logos in the footer are too much aligned to the left and right.

image

**Comment by acsnedegar** [comment]
1. Can we swap in square photos so they aren't cropped/have rounded edges with these:  https://lion.box.com/s/sih5zcebpxppkrsh9cqlsvz1b8z4uisc
Screen Shot 2021-02-19 at 5 16 43 PM

**Comment by acsnedegar** [comment]
2. All white alternating sections should be background hex: #FFFFFF
Screen Shot 2021-02-19 at 5 21 14 PM

**Comment by acsnedegar** [comment]
3. Hero text on mobile should be: 
font-family: Montserrat-Bold; 
font-size: 28px; 
letter-spacing: 0.1px; 
text-align: center; 
line-height: 29px;
Screen Shot 2021-02-19 at 5 26 04 PM

**Comment by acsnedegar** [comment]
4. Logo should go full width on mobile. 
5. Reorder hero elements to this order in comps (sorry Erik I just added you to this on invision) https://publicis.invisionapp.com/share/NKY61SDE97H#/screens/426553744
Screen Shot 2021-02-19 at 5 31 19 PM

**Comment by acsnedegar** [comment]
Who can join section: Icon is stretched on participating healthcare systems. I think i exported at the wrong size, can you please update with this file? Thanks! https://lion.box.com/s/a0x28phjuxbwm8as9f6lliwmnwhe7wos
Screen Shot 2021-02-19 at 5 42 41 PM

**Comment by acsnedegar** [comment]
7. Mobile should be ordered H1, body, then photo for those blocks. If possible
Screen Shot 2021-02-19 at 6 00 51 PM

**Comment by acsnedegar** [comment]
8. Who can join section on mobile breakpoint should stack and center like below: 
Screen Shot 2021-02-19 at 6 07 15 PM

**Comment by acsnedegar** [comment]
9. Padding can change to 40px on mobile instead of 60px
Screen Shot 2021-02-19 at 6 12 49 PM

**Comment by acsnedegar** [comment]
10. Is it possible to center align these blocks?
Screen Shot 2021-02-19 at 6 16 14 PM

11. Hover button color should be: #F9A921

12. Can the hero image have a retina option? Seems blurrier than others. https://lion.box.com/s/tjrpc1h05w3cq0rdwpoh7k7ykrpj0df8

**Comment by alinai** [comment]
At tablet,

1) Issue with alignment of content (text, image) on the page. See screen-shot to compare with the comp.

image

2) The font of Homepage tagline and title is too big compared to the comp.
image

3) The "How you can help" section title should align with the image per comp (tablet breakpoint)
image

**Comment by alinai** [comment]
On IE, the image and text in the Section "What the study is", "How you can help" and  "Learning from everyone" are all left aligned 

image

**Comment by claireblaustein** [comment]
When the button is activated, the button text color is hard to see (same as search icon), and the H2 changes styles, appearing normal instead of bold.

Screen Shot 2021-02-23 at 9 42 09 AM

**Comment by claireblaustein** [comment]
Also, all buttons should have text in all caps (footer is title)

Screen Shot 2021-02-23 at 9 46 26 AM

**Comment by alinai** [comment]
Desktop:
- A white space appears on scrolling down from the top....issue exists
- Hover button color should be: #F9A921...... not seeing the change
- Per comp, the font size for landing page body should be 18px....issue exists
image
-IE issues reported above exists
- A red spot/text is appearing at the background of homepage title
image



Mobile:
-The font size of "What the Study is" is different from comp


-The font size of heading and logos are different from comp - @acsnedegar , can you please check?
image

- The heading is almost touching the edges of the mobile device
image

- Logo should go full width on mobile....not seeing the change

**Comment by acsnedegar** [comment]
Erik this is looking great! Thank you! I have some things below that I found. 
1. Body still is showing as 16px, it should be 18px. 
Screen Shot 2021-03-02 at 3 12 46 PM
2. Also on tablet, you were right initially, that text should be center aligned vertically. My fault for not correcting that from Nadia's comment. 
Screen Shot 2021-03-02 at 3 30 01 PM
3. For me, the Connect logo in the hero on desktop is now showing some sort of pink "text" overlay? 
Screen Shot 2021-03-02 at 11 12 33 AM\
4. Logos are not responding on Mobile 
Screen Shot 2021-03-02 at 3 21 05 PM
5. Now that you have the icons folder, can you update the "To Top" button if you have time? 
Screen Shot 2021-03-02 at 3 42 39 PM
6. Phone number in footer should be the same style, bolded as the other footer items like "Accessibility"
Screen Shot 2021-03-02 at 3 46 35 PM
7. In safari, the lower section photos are getting squished in tablet/smaller desktop breakpoint
Screen Shot 2021-03-02 at 4 02 09 PM

**Comment by acsnedegar** [comment]
@alinai confirming here that the header size is ok as is. It should be 28px, bold which I am getting. Thanks for checking!

**Comment by acsnedegar** [comment]
In safari, the text block gets cut off in the "Who can Join" section at a smaller desktop/tablet size
Screen Shot 2021-03-03 at 3 13 06 PM

**Comment by alinai** [comment]
The image with "How can you help" looks too big at all breakpoints and the Back To Top button is too big.
image

**Comment by acsnedegar** [comment]
Replying to Nadia's comment above. Can the back to top button be 58px tall for size? 

The image size is because of how the tiled/paired images are designed in order to fit into the square aspect ratio. So I think it's ok as is since they appear to all have the same image slot size. 

Question - are we normally able to upload retina image options? It would be nice if we had those for people on Macs for example, for the photos specifically. I have the 2x sized images in that folder Erik in case we are able to add as a final touch. 

Looks great though! Thanks!

**Comment by erikscottmeyer** [comment]
We can use retina scale images for background images (and I do when I have them), but there's no way right now to upload retina scale media images.  I've been having problems getting the back to top svg to scale for some reason, so that was a known issue I'm still working on.  I believe all of the other feedback from earlier has been address except the IE11 problem.  Question, since IE11 is sunsetting at the end of the month, are we still supporting that?

**Comment by alinai** [comment]
Issues on Edge:
All nav titles are wrapping to next line including the "Join the study" button text.
image

**Comment by alinai** [comment]
Issues on IE:

-Horizontal scroll bar is appearing.
image

-No image is showing up for "How can you help"
image

image

**Comment by alinai** [comment]
On hovering both the "Join the study" buttons at mobile breakpoint, the one on the footer is getting white text color on hover but the top one is not at mobile breakpoint.

**Comment by acsnedegar** [comment]
Originally was thinking the text color would stay dark blue on hover on all breakpoints for the yellow buttons. Thanks!

**Comment by alinai** [comment]
@acsnedegar , do you think the spacing above and below the "Join the Study" button at  mobile breakpoint should be consistent?

image

**Comment by acsnedegar** [comment]
@alinai being consistent would be ideal. Might have been slightly off in the comps but if possible, doing 40px between each would be good. 

Also, one other thing for the menu - can we center the elements vertically within that navigation bar so the space on top is equal to the bottom? This might be a non issue once the right items are in there but just in case if we have time. Thanks!
Screen Shot 2021-03-15 at 9 56 29 AM

**Comment by acsnedegar** [comment]
On safari, two sections, "what the study is" and "learning from everyone" are underlining body copy on hover rather than just the heading.
Screen Shot 2021-03-15 at 11 28 20 AM
Screen Shot 2021-03-15 at 11 28 47 AM

**Comment by alinai** [comment]
I am seeing the difference in appearance of the underline on hovering the links in different browsers.

image
image

**Comment by acsnedegar** [comment]
Can the selected/highlighted nav box go be full height/edge to edge? Might not be an issue once things are back to one light for nav items but just flagging. Thanks! 
image

**Comment by blairlearn** [comment]
Replaced by PR #3052

**Pull request closed without merging**
