### PR TITLE
(#1607, #1608, #1609) Content Type specific css

### LINKED ISSUE #1197: Align Percussion content type specific styles to Drupal Content Types Styles
Inventory was completed in #1339.

### LINKED ISSUE #1607: Content Type specific references to be updated for Blog Pages
There are a couple of content type specific references to Blog pages that will need to be updated when migrating to the Drupal platform where these page hooks no longer exist.

New selectors will have to be used, or hooks added to Drupal content types to get these features working.

- ensure layout styles seen on `#nvcgSlSectionNav` in `blogs.scss` is now handled by twig templates.
- scope blogs post specific padding on `.contentzone` in `blog.scss` to blogPost entry point scss
- medium sized images are smaller on blogs. Adjust `figure.image-right-medium` in `blogs.scss` to be properly scoped to the blogPost entry point scss file
- scope `.cgvblogseries .list a.title {` font size styles in `bogs.scss` to blogSeries entry point scss
- replace `.topic-feature .cgvBlogPost a h3` in `blue.scss` with `.topic-feature .feature-card a h3`

### LINKED ISSUE #1608: Content Type specific references to be updated for Home and Landing pages
There are a couple of content type specific references to homelanding pages that will need to be updated when migrating to the Drupal platform where these page hooks no longer exist.

New selectors will have to be used, or hooks added to Drupal content types to get these features working.

- There were variations between home page and landing page accordions in `accordion.scss`, but now they share the same template so these styles can be consolidated and scoped to homelanding entry point scss
- scope margin on `.ncilandingpage p, .ncihome p:not(.site-name):not(.site-link)` elements in `homelanding.scss` to the homelanding entry point scss
- scope margin on `.ncilandingpage h1` in `homelanding.scss` to homelanding entry point scss
- scope `.ncilandingpage #PageOptionsControl1 ul` in `pageOptions.scss` to homelanding entry point scss
- properly scope `.ncilandingpage #PageOptionsControl1 ul` in `purple.scss`. The `.ncilandingpage` selector can probably be removed. Also check on blue and green color variants.

### LINKED ISSUE #1609: Content Type specific references to be updated for PDQ pages
There are a couple of content type specific references to PDQ pages that will need to be updated when migrating to the Drupal platform where these page hooks no longer exist.

- properly scope `.pdqcancerinfosummary table thead tr th` in `tables.scss` to pdq entry point scss

Acceptance Criteria:
1. ensure text in table header cells are centered on PDQ pages. For example `types/breast/hp/breast-screening-pdq`

### PR DESCRIPTION
**Pull request by alifr**
Closes #1607, closes #1608, closes #1609.

ODE: http://ncigovcdode130.prod.acquia-sites.com

### CODE REVIEW

**Comment by VictoriaSunNIH** [comment]
#1607 does not pass IA review. See ticket for comments.

**Comment by VictoriaSunNIH** [comment]
#1609 looks good.

**Comment by lburack** [comment]
#1608 also does not pass. See ticket for comments.

**Comment by VictoriaSunNIH** [comment]
These tickets are all looking good!

**Pull request closed without merging**
