### PR TITLE
(#909) Front-end Buildout of Green Microsite Palette

### PR DESCRIPTION
**Pull request by alifr**
Adding green theme color variant. 

Closes: #909 
Closes: #1655 

This PR includes a fix for the mobile nav menu, converting it to a flex layout so we're not dependent on fixed width floating items. This will allow us to accommodate a dynamic number of icons in the mobile nav.

### CODE REVIEW

**Comment by amydugan** [comment]
This can replace what is on the current Microsite ODE.

**Comment by VictoriaSunNIH** [comment]
Available on: http://ncigovcdode100.prod.acquia-sites.com/

**Comment by VictoriaSunNIH** [comment]
Currently awaiting client review before marking this as passed.  There are a few outstanding issues as well, but they will likely be taken care of outside this ticket (#1641, #1642, #1643)

**Comment by VictoriaSunNIH** [comment]
@alifr  - as discussed, please combine this with https://github.com/NCIOCPL/cgov-digital-platform/pull/1655 on an ODE so we can retest.

**Comment by VictoriaSunNIH** [comment]
This is looking good!

**Comment by alifr** [comment]
I'm going to rebase this branch to clean up the commit history.

**Comment by VictoriaSunNIH** [comment]
Looking good - passes review.

**Pull request closed without merging**
