### PR TITLE
Ticket 967, change date display in video form to checkbox.

### PR DESCRIPTION
**Pull request by adriancofie**
Changes  the date display in the video form to a checkbox.

#967

### CODE REVIEW

**Comment by adriancofie** [comment]
@bryanpizzillo  I've confirmed the text_textarea_with_summary change is not a fluke.

**Comment by VictoriaSunNIH** [comment]
ODE: http://ncigovcdode70.prod.acquia-sites.com/

**Comment by VictoriaSunNIH** [comment]
Date display looks good, but dates are not displaying on the front-end.

Failing this PR for now.

**Comment by VictoriaSunNIH** [comment]
@adriancofie - This PR should be closed, and then implemented in a feature branch to include all video updates here https://github.com/NCIOCPL/cgov-digital-platform/issues/1314

**Comment by adriancofie** [comment]
Note: Merge this branch with whatever ticket is created to address #1314. This PR was created to address one discrete item within #967- i.e. change  the date display in the video form to a checkbox.

**Pull request merged**
