### PR TITLE
Cancer center styling and display issues

### LINKED ISSUE #1846: Cancer Center - Phone Label Field Does Not Correctly Display Punctuation
On the Cancer Center content type, if you add punctuation in the Phone Label field, it shows the Unicode. The expected behavior is that the actual punctuation mark display.

This was inputted in the Drupal form:
Screen Shot 2019-05-30 at 3 22 29 PM
This is what displays on the front end:
Screen_Shot_2019-05-30_at_3_21_02_PM

### LINKED ISSUE #1890: Cancer Centers - Styling Issues
Found some minor, low priority issues with the Cancer Center content type:

- If two separate phone numbers are provided, there should only be a single line break between the two lines (see screenshot comparison below)
- If a city and state are provided by the CMS user, a comma automatically appears between the two. There's an extra space between the city and the comma (see screenshot comparison below)
- On production, the state name is currently fully spelled out, but on the ODE, the state abbreviation displays. We should implement what's currently on the live site, so the full state name should display.

cancer-center-compare

### PR DESCRIPTION
**Pull request by arcepaul**
Closes #1846 .
Closes #1890 .

- [x] 1846 - This was not isolated to just the phone label field so I moved cancer center templates to use twig field value which handles these more easily.  This template was completed before twig field value module was incorporated.

- [x] #1890 - Cancer centers styling issues

### CODE REVIEW

**Comment by arcepaul** [comment]
@lburack @VictoriaSunNIH 
ODE Available at: http://ncigovcdode161.prod.acquia-sites.com/

**Comment by lburack** [comment]
This is working as expected now. Thanks, @arcepaul !

**Comment by arcepaul** [comment]
@lburack @VictoriaSunNIH 
This ODE has been updated with the new fixes

**Comment by lburack** [comment]
Thanks, @arcepaul. #1846 is still fixed here and #1890 looks good too. Passes IA review!

**Pull request closed without merging**
