### PR TITLE
Add and enable Cgov Utility form tools service. Limit article text formats

### PR DESCRIPTION
**Pull request by adriancofie**
TIcket #835. Ability to limit text formats
* Adds and enables the Cgov Utility module
* Limits article WYSIWYG fields to allowed text formats
* Updates row size for Article body content field

### CODE REVIEW

**Comment by adriancofie** [comment]
On http://ncigovcdode47.prod.acquia-sites.com/

**Comment by lburack** [comment]
On an Article for both an editor and admin, the Streamlined and Full WYSIWYGs did not display the bullets in the field. On the front-end of the page, I see the bullets, but it's odd that bullets do not display in the field. Numbers from an ordered list do show, however. 

In the bottom left of the wysiwyg, I do see `body ul li`but is there a reason why the bullets themselves do not display, @adriancofie?

Screen Shot 2019-03-24 at 11 04 08 PM

**Comment by adriancofie** [comment]
@lburack  Not sure why, it could have to do with our admin theme / it's CSS. If req'd I would open up a separate ticket.

**Comment by lburack** [comment]
@adriancofie @VictoriaSunNIH  - I've opened up #1238 for this issue with the bullets not showing in the field.

**Pull request merged**
