### PR TITLE
ticket/1146 Fix Display for Two Item Feature Card

### PR DESCRIPTION
**Pull request by alifr**
add feature card styles for mini-landing pages #1146

### CODE REVIEW

**Comment by alifr** [comment]
testable on the `/about-nci/organization/ccct` page and `/pets` page

**Comment by lburack** [comment]
Hi @alifr, the feature cards are looking pretty good, but the hover state is not correct:
- on hover, the card should not lighten or darken. Please remove the lightened hover state.
- on hover of any part of the card, the link title should change to cranberry.

Here are examples from the live site: 
https://www.cancer.gov/about-nci/organization/ccct (two item feature cards)
https://www.cancer.gov/about-cancer/treatment (inline feature card example)

**Comment by lburack** [comment]
This now passes IA review. Thanks, @alifr!

**Comment by bryanpizzillo** [comment]
Closing as these items were rolled into #1299

**Pull request closed without merging**
