### PR TITLE
Merge "feature/field-fixes" into develop

### LINKED ISSUE #844: Blog Post - Changing Posted Date Not Reflected on Front-End
I created a blog post with a Posted Date of 2-20-2019. I published the blog post. 
I then put the blog post back into Editing and changed the date to 12-18-2018. I saved my changes and pushed the updated blog post to Published. 
On the front-end, the date on the blog post still says 2-20-2019. It should have 12-18-2018 as its posted date though.

### LINKED ISSUE #858: Update Pretty URL helper/tooltip text on Blog Series
The blog series is not using the [common fields pretty URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Pretty-URL) helper text. 

I'd actually like to use the following tooltip text for the pretty URL on the Blog Series (and only the blog series):
_Used as the last segment of the URL, not including slash. Leave blank if blog series is the designated landing page in the site section._

Not sure if this one goes to @daquinohd or @blairlearn.

### LINKED ISSUE #862: Feedburner URL Helper Text on Blog Series
The second bullet on the Feedburner helper text on the Blog Series should be removed. It was not part of the [tooltip text on the wiki](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Series#feedburner-url)

**Remove the following:**
 _Start typing the title of a piece of content to select it. You can also enter an internal path such as /node/add or an external URL such as http://example.com. Enter <front> to link to the front page._

### LINKED ISSUE #912: Blog Series - Make 'Allow Comments' Should Be a Dropdown
Please change the 'Allow Comments' checkbox to be a dropdown. This is because checkboxes in Drupal don't have headings which provides a less than optimal UX for the UI.

### PR DESCRIPTION
**Pull request by daquinohd**
Merge "ticket/field-fixes" into "origin/feature/field-fixes"
* Changed field_allow_comments to dropdown (closes #912)
* Blog Series field_pretty_url tooltip/helper text (closes #858)
* Set correct helper text for FeedBurner link (closes #862 )
* Fixed date field display in template. (closes #844)

### CODE REVIEW

**Comment by daquinohd** [comment]
@lburack @VictoriaSunNIH - this is ready for review on ncigovcdode35.prod.acquia-sites.com.

**Comment by lburack** [comment]
@daquinohd – your 2nd, 3rd, and 4th bullets look good to me (#858 , #862 , #844 )
Just one thing about the 1st one for #912  — field_allow_comments is now a dropdown, but there's an option for 'None'. I was able to select this, but I'm not sure what would happen. I think this should only have two options:
* Allow Comments
* Do Not Allow Comments (default to this option)

**Comment by daquinohd** [comment]
@lburack - dropdown is updated.

**Comment by lburack** [comment]
Allow/Do Not Allow Comments dropdown is looking good. Thanks, @daquinohd

**Comment by VictoriaSunNIH** [comment]
Looks good to me too!

**Pull request merged**
