### PR TITLE
cts pkg update to 0.8.2

### PR DESCRIPTION
**Pull request by arcepaul**
- incorporates Bryan's tests for trial search query and query string building
- router changes to use basename
- added expand/collapse all for accordions on trial description page
- removed failing tests and snapshots
- updated display mapping for trial phases and trial types
- added scroll to top on clear form
- 0 as age displays error
- helper text for age on advanced form updated
- helper text removed from sticky block on advanced
- filtering by state on trial description displays state name
- default list for location sites is defaulted to United States and not all
- search criteria hidden on trial description when visiting trial description page via link
- switching between advanced and basic forms clears out store data
- loading skeletons added to results and trial description pages

### CODE REVIEW

**Comment by arcepaul** [comment]
@VictoriaSunNIH @lburack 
An ODE with the latest is available at : http://ncigovcdode302.prod.acquia-sites.com/about-cancer/treatment/clinical-trials/search/

**Comment by VictoriaSunNIH** [comment]
A few things:

- Clear form takes me to http://ncigovcdode302.prod.acquia-sites.com/advanced which....is a page not found
- There's a weird bracket at the bottom of the trial desc pages
- I can no longer go "back to search" on the trial desc pages
- The trial type mapping is still not correct for health services research
- When I go to a trial desc page, the location still defaults to US but shows all

**Comment by VictoriaSunNIH** [comment]
@arcepaul, @lburack 
For Zipcode:
If i enter invalid criteria, the form should not allow me to submit "Find Trials".  Right now, I can enter abcde, and still submit the search and get back results, even though it does validate on the field and give me the red error box.

For Age:
If i enter invalid criteria, the form should not allow me to submit "Find Trials".  Right now, I can enter abc, or 0, and still submit the search and get back results, even though it does validate on the field and give me the red error box.

**Comment by arcepaul** [comment]
@VictoriaSunNIH @lburack 
Updated with meta tag updates.  All issues in previous comment should be addressed. US site locations as default should be fixed with this version, as well as the clear form reloading the page.  Weird bracket at bottom of description is gone as well.  Back to search should now appear on description pages.

As for the age validation, temporarily I have made it like the zip code whereby if you enter a bad age, you can hit Find Trial and it will do the search as if that input was never entered.  This is because we need to figure out the form error handling incorporating changes from Bryan's work to be incorporated.

**Comment by VictoriaSunNIH** [comment]
@arcepaul:

1. when i enter an invalid age, and get the validation error, then enter a second invalid age, the second age is not showing as invalid.

2. When i search for all results, I only get a start over option, with no "Back to search results".   This should also appear on the trial description page when i have searched for all results, and not only for searches with criteria.

**Pull request merged**
