### PR TITLE
Home/Landing, Mini-landing and CTHPs for NCIDS

### LINKED ISSUE #3380: Story: Update Mini Landing Pages for NCIDS Layout
## As a user, I would like to view Mini Landing Page content using the NCIDS, so that I have a better navigation experience.

This ticket is to update the mini landing page template which uses the default page layout, i.e. the layout with a side nav on the left and a content area on the right.

As part of this ticket, the Inner Pages background color should be updated to be #FFFFFF

> **ESTIMATE** 8

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [x] #3240
- [x] #3375

### Tasks
- [ ] Setup mini landing page entrypoint
   - You will need to update the ncids_trans.libraries.yaml to change the "entry points" to have a dependency on ncids-global instead of the legacy-global.
- [ ] Update `templates/content/mini_landing/page--cgov-mini-landing--full.html.twig` to match the Spike template
- [ ] Update the node templates (listed below) to:
   - swap out old container divs with new ones
   - update the main-content ids (so the skipnav works) 
   - add the legacy wrapper
   - remove the page options. This should be removing `{{ drupal_block('page_options') }}` in most cases.
- [ ] Fix the reference to monte in the scss

#### Node templates
- [ ] `templates/content/mini_landing/node--cgov-mini-landing--full.html.twig`
  - Mini Landing with List with Images: https://www.cancer.gov/about-cancer/coping
  - Mini Landing with content: https://www.cancer.gov/types/liver
  - Mini Landing with Dynamic List: https://www.cancer.gov/news-events/press-releases/2022
  - Mini Landing: https://www.cancer.gov/types/by-body-location
  - DCEG Mini Landing with Dynamic List: https://dceg.cancer.gov/news-events/events/past-events
- [ ]  `templates/content/mini_landing/field--paragraph--cgov-two-item-feature-row.html.twig`
  - https://www.cancer.gov/research/cancer-research-partners/research-studies
  - https://www.cancer.gov/about-nci/organization/ccct

### Technical Notes
* `templates/content/mini_landing/page--cgov-mini-landing--full.html.twig` is a new file for this theme

### LINKED ISSUE #3383: Story: Update Home/Landing Pages for NCIDS Layout
## As a user, I would like to view Home/Landing Page content using the NCIDS, so that I have a better navigation experience.

This ticket is to update the home/landing page template which uses a full-page layout without left navigation.

As part of this ticket, the home and landing pages background color should be updated to base-lightest (#F0F0F0)
  - Replaces the tannish background color on current home and landing pages (current page: https://www.cancer.gov/) should be the background color from the bottom of the header/mega menu until the top of the footer, minus the multimedia row that will stay as is (teal background)
  - Replaces the background "sides" on special report template pages (AP, NCA50, Patient Portal) but the current body container white background, header, and footer should stay the same (current page: https://www.cancer.gov/research/annual-plan)

> **ESTIMATE** 8

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [x] #3240

### Tasks
- [ ] Setup ncids-common.scss to pull in the NCIDS
   - This includes pulling in legacy css
- [ ] Setup any of the other entry points (if needed, but they are usually blank)
   - You will need to update the ncids_trans.libraries.yaml to change the "entry points" to have a dependency on ncids-global instead of the legacy-global.
- [ ] Update page templates (listed below)  to match the Spike template
- [ ] Update the node templates (listed below) to:
   - swap out old container divs with new ones
   - update the main-content ids (so the skipnav works) 
   - add the legacy wrapper
   - remove the page options. This should be removing `{{ drupal_block('page_options') }}` in most cases.
- [ ] #3418
  - break out node template between normal home/landing and special report (dceg should die) 

#### Page Templates
- [ ] `templates/content/home_landing/page--cgov-home-landing.html.twig`
  - https://www.cancer.gov
  - https://www.cancer.gov/types
  - https://www.cancer.gov/news-events
  - https://www.cancer.gov/espanol
  - https://dceg.cancer.gov/
- [ ] `templates/content/home_landing/page--cgov-home-landing--special-report.html.twig` ???????????
  - https://www.cancer.gov/news-events/nca50?cid=wl_int_en_ccblog_nca50 
  - https://www.cancer.gov/research/annual-plan
  - https://www.cancer.gov/research/cancer-research-partners

#### Node Templates
- [ ] `templates/content/home_landing/node--cgov-home-landing--full.html.twig`

### Technical Notes
- DCEG will not use the existing template in new theme
- Home and landings should not have page options in new theme
- The logic within the twig files may need to be redone, as Home does not have a page title, and removing the page option block will change the page style
- base-lightest (#F0F0F0) should be the background color from the bottom of the header/mega menu until the top of the footer, minus the multimedia row that will stay as is (teal background)

### LINKED ISSUE #3384: Story: Update CTHPs for NCIDS Layout
## As a user, I would like to view CTHP content using the NCIDS, so that I have a better navigation experience.

This ticket is to update the CTHP template which uses a full-page layout without left navigation.

As part of this ticket, the Inner Pages background color should be updated to be the same for the Health Professional and Patient Version: base-lightest (#F0F0F0). 

> **ESTIMATE** 8

### Acceptance Criteria

```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [x]  #3240

### Tasks

- [ ] Setup ncids-common.scss to pull in the NCIDS
   - This includes pulling in legacy css
- [ ] Setup any of the other entry points (if needed, but they are usually blank)
   - You will need to update the ncids_trans.libraries.yaml to change the "entry points" to have a dependency on ncids-global instead of the legacy-global.
- [ ] Update page templates (listed below)  to match the Spike template
- [ ] Update the node templates (listed below) to:
   - swap out old container divs with new ones
   - update the main-content ids (so the skipnav works) 
   - add the legacy wrapper
   - remove the page options. This should be removing `{{ drupal_block('page_options') }}` in most cases.
- [ ] fix any |trans tags.

#### Page Templates
- [ ]  templates/content/cthp/page--cgov-cthp.html.twig
  - https://www.cancer.gov/types/lung
  - https://www.cancer.gov/types/leukemia
  - With research list card: https://www.cancer.gov/types/brain

#### Node Templates
- [ ] templates/content/cthp/node--cgov-cthp--full.html.twig

### Technical Notes
- Foundation can be replaced on the cards, but are many different types of cards and card combinations

### LINKED ISSUE #3418: Add theme suggestion to Node templates for Home/Landing field_page_style field
For page templates we use the field_page_style field on Home/Landing to add suggestions for page templates. This allows us to have different markup for those templates. For the node template however it is a mess of conditional statements based on the contents of that field. This ticket is to add a theme suggestion for node templates to provide a way to have separate, and cleaner, node templates. (This will be implemented as part of ncids, the cgov_common legacy theme will not implement this.)

### PR DESCRIPTION
**Pull request by bryanpnih**
ODE: http://ncigovcdode479.prod.acquia-sites.com

Closes #3418
Closes #3383 
Closes #3380
Closes #3384

### CODE REVIEW

**Comment by mworrest** [comment]
1. The footer icons are not accurate. This is being worked on in another ticket.
2. Top and bottom page options are up against each other. Add some space between the icons.
3. Left nav arrow icon not centered. This is being worked on in another ticket.
4. Hero with text - text is too close to edge of image. Add 38px left padding.
5. Special character in page title showing oddly in breadcrumbs https://ncigovcdode479.prod.acquia-sites.com/research/key-initiatives/nci-equity-inclusion-program/funding
6. Cancer Types landing page--make background white: https://ncigovcdode479.prod.acquia-sites.com/types

**Comment by meglake** [comment]
@bryanpizzillo updates for you:
* Reviewed Cancer Types with @mworrest, and all looks good. Will add to my list for items to review with the client.
* Reviewed G&T Spanish page (https://ncigovcdode479.prod.acquia-sites.com/espanol/subvenciones-capacitacion) with @mworrest  and agree that this should be handled like Cancer Types (white background)

Testing Next Steps:
* @mworrest will do a thorough review of all Spanish home & landing and at various breakpoints
* @lburack will do a thorough review of mini landing and CTHP in English and Spanish and at various breakpoints
* @meglake  will conduct an overall review of home, landing, mini landing, CTHP in English/Spanish at various breakpoints and various browsers 
* All testing feedback due on this ticket asap this week.

**Comment by meglake** [comment]
@bryanpizzillo, me testing notes below:
**Home/Landing Pages:**
- Body content is the same width as the hero image on ODE (smaller width on PROD). Or the hero image is too small on ODE. Is this expected or a bug?

**Home Page:**
- DOC carousel pagination circles are up against the DOC cards (see screenshots)
ODE:
ODE Cgov DOC Carousel
PROD:
PROD Cgov DOC Carousel

**CTHPs:** (known issues, recording for reference)
* Long titles get overlapped by patient/health provider button when in smaller break points
* When breakpoint gets small enough that the patient/health provider button turns into a link under the title, it has a different background color than the rest of the page

**Comment by bryanpizzillo** [comment]
@meglake I see what the issue is for CTHP titles and the audience toggle. It *is* the page options, they allow the button to drop to the next line. However, can we just do what is in the image below? Basically it removes the positioning of the button to account for the page options. Since we have no page options there, we probably should not have to account for the spacing.

image

**Comment by bryanpizzillo** [comment]
@meglake 
> Body content is the same width as the hero image on ODE (smaller width on PROD). Or the hero image is too small on ODE. Is this expected or a bug?
Let me see what I can do. Letting it stretch was causing a lot of issues, in fact it is what precipitated turning off widescreen.  So I turned off the CSS for allowing it to grow, and the page showed up "correctly"

The CTHP issue with the toggle should be fixed now.

**Comment by meglake** [comment]
@bryanpizzillo, recap from internal testing:

1. Hero text - Not yet fixed. Please update total width to 30% 
2. Cancer types background color - Fix approved
3. G&T Spanish background color - Fix approved
4. CTHP Mobile accordion +/- coloring - Fix approved
5. Home/Landing Body content same width as hero - Review with client and request to accept as is.
6. Home page DOC carousel pagination circles - Not yet fixed. Note as known issue to client for their testing.
7. CTHP patient/health provider button turns into a link under the title, it has a different background color - Fix approved
8. CTHP button overlap title - Fix approved

**Comment by bryanpizzillo** [comment]
@meglake and @mworrest 1 & 6 are now fixed on the ODE.

**Comment by meglake** [comment]
Confirmed fixes and updated my note from yesterday. We will get # 5 approved by the client to leave as is or put in a request to change after the walkthrough on 7/14.

**Comment by meglake** [comment]
Per client walkthrough on 7/14 the following items have been approved as is for home/landing, mini landing, and CTHPs:
- Home/landing pages
-- New grey background (with exception of Cancer Types and Grants & Trainings landing pages)
-- Hero image and body content are same width at widescreen
- CTHPs
-- New grey background color for both patient and healthcare provider CTHPs
- Mini landing
-- list item title links and feature card title links will maintain cranberry rollover color (as agreed upon in inner page review)

Client will conduct their further review between now and 7/21. Will update based on their feedback.

**Review by arcepaul — APPROVED** [review]
LGTM.  nice work on CTHPs

**Comment by bennettcc** [comment]
@bryanpizzillo This has passed tech, product, and client review - plz merge to develop

**Review by bryanpizzillo — APPROVED** [review]

**Pull request merged**
