### PR TITLE
Feature/cgov 65 create basic roles

### LINKED ISSUE #65: Create Basic Roles
See https://github.com/bryanpizzillo/cgov-digital-platform/wiki/Editorial-Workflow

### PR DESCRIPTION
**Pull request by bgnih**
Closes #65 - Creates new roles, adds tests that they exist, and updates non-content-type permissions on new roles, updates permissions for authenticated and administrator users (in the cgov_site profile/config/install) to make site usable for non-User1 admins.

### CODE REVIEW

**Comment by bryanpizzillo** [comment]
@bgnih Can you please update your branch with develop so that the status checks can pass?

**Comment by bgnih** [comment]
updated and passing

**Comment by VictoriaSunNIH** [comment]
@bryanpizzillo here - did you rebase from develop?

**Comment by bgnih** [comment]
I rebased it (hopefully correctly) - can you confirm?

**Comment by bgnih** [comment]
I think I merged this by doing a `git push upstream`.  oops.  (still learning my away around forking :-( )

**Comment by BrendanBeltzNIH** [comment]
Yeah, the flow is:

origin = your fork on github
upstream = original repo on github

Pull:
git fetch upstream/develop
git checkout develop
git merge upstream/develop (If you have no conflicts it's a fast-forward merge - you should have no conflicts since you don't touch your local develop anymore)
(HERE is where you might then go to your local feature branch and rebase on top of your local develop after updating from upstream - or just a normal merge if you're past the point of rebase (IMHO better than rebasing directly onto the upstream/develop))

Working branch:
git checkout develop
git checkout -b new-feature-branch-name
..changes..
git push --set-upstream origin new-feature-branch-name

Then go to github and PR into the original repo from your feature branch on the fork. Rinse and repeat.

**Comment by BrendanBeltzNIH** [comment]
yeah

**Pull request merged**
