### PR TITLE
(#3007) Glossary Term Links on HP Summaries

### PR DESCRIPTION
**Pull request by sarinapadilla**
* Update syntax for passing query params to axois get request
* Update spelling error in error message :)

### CODE REVIEW

**Review by venglisch — APPROVED** [review]
Ausgezeichnet!  Danke schoen!

**Comment by blairlearn** [comment]
Is this on an ODE somewhere?

**Comment by sarinapadilla** [comment]
@blairl-nih @venglisch switching code ran soooo slowwww but finally there is an ODE for testing: https://ncigovcdode402.prod.acquia-sites.com/

**Comment by venglisch** [comment]
Perfect! It works as expected for the IACT HP summaries.  A sanity check for glossary pop-ups in patient summaries checked out OK as well.

**Review by blairlearn — APPROVED** [review]

**Review by blairl-nih — APPROVED** [review]

**Pull request merged**
