### PR TITLE
Accessibility issues for hotfix

### LINKED ISSUE #2225: Accessibility: skipnav missing main-content target
The site skipnav does not work because it is missing the 'main-content' id.  This problem exists in production on cgov.

Add the main-content id to main.

### LINKED ISSUE #2226: Accessibility: screen reader text is invisible to screen reader
The .hidden class is being applied to some elements with the intention of being a sr-only|show-for-sr class but a display: none is being applied to it by one of the stylesheets, making it invisible to screenreaders.

This issue exists in production.

(ex. search button icon )
hidden

### LINKED ISSUE #2227: Accessibility: Megamenu is invisible to screenreaders
On the megamenu ul, the aria-hidden attribute is set to true, meaning that it cannot be seen by screenreaders.  The hidden attribute should be toggled alongside the megamenu's visibility but is hardcoded as true.

This issue exists in production.

Toggle the aria-hidden attribute with megamenu visibility.

Screen Shot 2019-07-18 at 5 02 26 PM

### PR DESCRIPTION
**Pull request by arcepaul**
Closes #2225 
Closes #2226 
Closes #2227 

#2225: Changed the target for skipnav to #target.  Couldn't change to main-content because several scripts were already keyed to #content. 
#2226: Using existing class 'show-for-sr' for screenreader text instead of 'hidden' which was getting display: none and in actuality hiding text from the screen reader.  Steps to replace the class in block content need to be made as well.
#2227: removed aria-hidden attribute

### CODE REVIEW

**Comment by arcepaul** [comment]
@lburack @VictoriaSunNIH 
ODE available at: http://ncigovcdode234.prod.acquia-sites.com/

**Comment by VictoriaSunNIH** [comment]
@arcepaul  - not sure how we would test this one.  is a code review more appropriate/good enough?

Also - we can help with block content clean up, just need to understand what to change.  thanks!

**Comment by arcepaul** [comment]
@VictoriaSunNIH 
Ok.  The easiest bits would just be testing the skiplink and running through the site with a screenreader.

In terms of changes for the content block, we would need to swap out the class="hidden" with class="show-for-sr" in cases where it is text meant for a screenreader.  (ex. Footer icon links read out "social media" instead of what it's actually linking to.

**Comment by markecramer** [comment]
These 3 items, 2225, 2226 and 2227 look good to me. Thanks Paul!

**Comment by bryanpizzillo** [comment]
@VictoriaSunNIH We good on this? (i.e. there were no visual regressions?)

**Comment by VictoriaSunNIH** [comment]
Yes - we good @bryanpizzillo

**Pull request merged**
