### PR TITLE
Feature/blog series list views (#1016)

### LINKED ISSUE #827: Blog Series List Views
The blog series list view should allow us to choose one of two display options:
* Thumbnail image | Item Title (blog post title) | Date & Byline | List Description | Continue Reading Link
* Item Title (blog post title) | Date & Byline | List Description | Continue Reading Link

For the second option, the content should over to the left to fill up the space where the image is missing.

### LINKED ISSUE #975: Create Blog Series templates
## Description 
Add twig templates for the cgov_blog_series content type. Currently, only the Blog Post list view shows up on Blog Series pages; the template should display the Banner Image, Intro Text, and Featured Posts. 

This ticket just involves getting the field data onto the page - the look and feel components will be handled in #785.

### PR DESCRIPTION
**Pull request by daquinohd**
(Closes #975) 
* Update blog series template
* Remove intro_text and body fields
* Add public_use (will work when #860 is merged to develop)
* Fixed yaml_content

(Closes #827)
* Renamed page_manager variants
* Added layouts and configurations for page manager
* Translation & layout plugin name change
* Set HTML column structure for blog post & series
* Added translation for 'continue reading' and 'by'
* Configured thumbnail crop for Blog Series list
* Configured date format for all blog content
* Added blog_macros.twig

### CODE REVIEW

**Comment by daquinohd** [comment]
ODE: ncigovcdode46.prod.acquia-sites.com

**Comment by daquinohd** [comment]
@lburack @VictoriaSunNIH - this ticket just covers the Blog Series list functionality. The styling, right rail, and other Blog Series elements are not in a pretty state. 

Each Blog Post list item should display the expected title, list description, date/author byline, continue reading link, and translations for the date, "by", and "Continue Reading". The thumbnail images are shown by default, but I can create a thumbnail-free variant if you want to take a look.

**Comment by lburack** [comment]
@daquinohd @VictoriaSunNIH  - I've found some issues:
- For my [blog post](http://ncigovcdode46.prod.acquia-sites.com/research/key-initiatives/ras/ras-central/blog/blog-list-test) on this [blog series](http://ncigovcdode46.prod.acquia-sites.com/research/key-initiatives/ras/ras-central/blog), I added a promotional image and not a lead image. The promotional image should be the one that is pulled in as the thumbnail on the blog series. I am not seeing it display though.
- on the date/byline, the comma that appears after the date has an unnecessary space; it should display directly next to the year (it's showing as March 11, 2019 , by Lindsay Burack)
- For Spanish, the month is appearing correctly, but the format of the date is not. In Spanish, the date should appear first — 11 de marzo de 2019 — but what I'm saying on the ODE is "Marzo 11, 2019"
- Spanish byline is not translated correctly. I see ', by' when it should be 'por' (no comma)
- 'Continue Reading' is not translated for Spanish

**Comment by daquinohd** [comment]
This is being closed and replaced by #1042.

**Pull request closed without merging**
