### PR TITLE
 (#2774, #2785, #2794, #2775  )Special Report Template and Borderless Card

### LINKED ISSUE #2774: Story: Special Report Template for AP
## As a member of NCI Leadership, I would like to have a unique layout for the AP content, so that it may appear fresh and increase viewing times 

> **ESTIMATE** 

### Acceptance Criteria

```gherkin
Scenario: User views the AP landing page 
  Given the user is viewing the AP landing page 
    And the browser width is 1025px or greater 
  Then the Desktop Hero image should be displayed full width 
    And the page title should appear on top of the desktop hero image, centered over the main content area 
    And the main content area should overlap the bottom of the hero image 
    And no left navigation will display 
```

```gherkin
Scenario: User views the AP landing page on Tablet 
  Given the user is viewing the AP landing page 
    And the browser width is 1024px or less 
  Then the Desktop Hero image should be displayed full width 
    And the page title should appear on top of the desktop hero image, centered over the main content area 
    And the main content area should appear below the hero image 
```

```gherkin
Scenario: User views the AP landing page on Mobile 
  Given the user is viewing the AP landing page 
    And the browser width is 640px or less 
  Then the Tablet Hero image should be displayed full width 
    And the page title should appear on top of the hero image, centered over the main content area 
    And main content area should appear below the hero image 
```

```gherkin
Scenario: Content owner creates a new Special Report landing page  
  Given the user is logged in as an editor 
    And the user adds new content 
    And selects “Home and Landing” as the content type 
  Then a new Home and Landing page is created 
    And a dropdown with the title “Home and Landing Page Style” appears under the language selection and above the site section  
    And under the dropdown the tooltip text appears that reads "Select a template for the page" 
    And the dropdown defaults to "- Standard -" 
    And the dropdown has two options of "Standard" and "Special Report" 
    And the field is required 
```

```gherkin
Scenario: Content owner does not need to enter tagline 
  Given the user is logged in as an editor 
  When the user is creating a Home and Landing page 
    And the user selects "Add Hero Banner" 
  Then upload fields appear for the Desktop Hero and Tablet Hero 
    And a field for Tagline appears 
    And the tagline field has help text that reads "Appears on top of the hero image for Home and Landing pages using the Standard template" 
    And the tagline field is not required 
```
**Analytics** 

```gherkin
Scenario: Page load of AP landing page
Given user views the AP landing page
 Then the following parameters should be captured
      | parameter | value                                                                                                                                                                                                                                                                                                                                                                                               |
      | event1    |                                                                                                                                                                                                                                                                                                                                                                                                     |
      | prop1     | [full URL 1-100]                                                                                                                                                                                                                                                                                                                                                                                    |
      | prop6     | [short title]                                                                                                                                                                                                                                                                                                                                                                                       |
      | prop8     | [language]                                                                                                                                                                                                                                                                                                                                                                                          |
      | prop10    | [browser title]                                                                                                                                                                                                                                                                                                                                                                                     |
      | prop26    | [timestamp]                                                                                                                                                                                                                                                                                                                                                                                         |
      | prop29    | /(year)=(19\|20)\d{2}\s\|\s(month)=(?:Jan(?:uary)? \|Feb(?:ruary)? \|Mar(?:ch)? \|Apr(?:il)? \|May \|Jun(?:e)? \|Jul(?:y)? \|Aug(?:ust)? \|Sep(?:tember)? \|Oct(?:ober)? \|(Nov \|Dec)(?:ember)?)\s\|\s(date)=\d{1,2}\s\|\s(day)=(?:Sun(?:day)? \|Mon(?:day)? \|Tue(?:sday)? \|Wed(?:nesday)? \|Thu(?:rsday)? \|Fri(?:day)? \|Sat(?:urday))\s\|\s(time)=(1[0-2]\|0?[1-9]):([0-5][0-9]) ?([AP][M]) / |
      | prop42    | [font size]                                                                                                                                                                                                                                                                                                                                                                                         |
      | prop61    | [previous page value]                                                                                                                                                                                                                                                                                                                                                                               |
      | prop65    | [page load time]                                                                                                                                                                                                                                                                                                                                                                                    |
      | eVar2     | D=c8                                                                                                                                                                                                                                                                                                                                                                                                |
      | evar5     | [screen breakpoint]                                                                                                                                                                                                                                                                                                                                                                                 |
      | evar1     | [page url]   
```

```gherkin
Scenario: Events for page depth
Given user is viewing the AP landing page
When user scrolls beyond 50% point of page body (excluding main nav and footer)
Then event is fired
  And the following parameters should be captured
      | parameter | value             |
      | event20   |                   |
      | prop66    | page-scroll |
      | prop8     | [language]        |
```

### Resources:
Mockups
- Desktop: https://publicis.invisionapp.com/share/DZWC0VL2B3E#/410081138_AP_Landing_Page_V9_-_Desktop

- Tablet 1024:  https://publicis.invisionapp.com/share/DZWC0VL2B3E#/415867266_AP_Landing_Page_V9_-_Tablet_1024

- Mobile: https://publicis.invisionapp.com/share/DZWC0VL2B3E#/411216125_AP_Landing_Page_V9_-_Mobile


### Notes

*Some complementary notes if necessary:*
prop29 format : year=2020 | month=June | date=1 | day=Monday | time=3:46 PM

- Page Style specs in wiki https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Home-&-Landing-Page#page-style


---

## Solution

### Tasks
- [ ] Augment the Landing Page Content Type (#2785) 
        - [ ] Add new field for template style
        - [ ] Add Theme Suggestions
        - [ ] Add YAML Content  
- [ ] Create new twig template (#2794)
        - [ ] Create Template
        - [ ] Create styles for page options
        - [ ] Add layout styles
        - [ ] Create webpack entrypoint

- [ ] Add analytics for page options (add ACs to story)

### LINKED ISSUE #2775: Story: Borderless Full-Width Card
## As a content editor, I would like to be able to embed a borderless full-width card, so that we can promote the most important information effectively. 

> **ESTIMATE** 

### Acceptance Criteria

```gherkin
Scenario: User views a page with a borderless full-width card on desktop or tablet 
  Given a user is viewing the AP landing page 
    And the browser width is 768px or greater 
  Then a borderless full-width card should appear 
    And the page title of the selected feature card item should appear as a H2 
    And the title will turn cranberry when the user hovers over it 
    And the title will link to the selected feature card item 
    And the card description of the selected feature card item should appear under the card title 
    And a button will be displayed under the card description with the card’s button text field and a right pointing carat icon 
    And that button will contain screen reader text containing the button title text 
    And that button will link to the selected feature card item 
    And the 1:1 crop of the promo image of the selected feature card item should appear to the right of the title and text (following our image rules) 
    And the image will link to the selected feature card item 
```

```gherkin
Scenario: User views a page with a borderless full-width card on mobile 
  Given a user is viewing the AP landing page 
    And the browser width is 640px or less 
  Then a borderless full-width card should appear 
    And the card title of the selected feature card item should appear as a H2 
    And the title will turn cranberry when the user hovers over it   
    And the title will link to the selected feature card item 
    And the 1:1 crop of the promo image of the selected feature card item should appear (following our image rules) under the title 
    And the image will link to the selected feature card item 
    And the card description of the selected feature card item should appear under the image 
    And a button will be displayed under the card description with the card’s button text field and a right pointing carat icon 
    And that button will contain screen reader text containing the button title text 
    And that button will link to the selected feature card item 
```

```gherkin
Scenario: User views a Spanish page with a borderless full-width card 
  Given language is set to "ES” 
  Then Spanish translated content of all fields will display 
```

```gherkin
Scenario: Content editor adds a borderless full-width card to the AP landing page 
  Given the user is logged in as an editor 
    And the user edits the AP landing page 
    And expands the drop down to add a paragraph to Contents 
    And selects "Add Borderless Full Width Card" from the list 
  Then the fields for a borderless full width card appear 
    And the featured Item picker appears 
    And the Override Card Title field appears 
    And the Override Card Description field appears 
    And the Override Promotional Image picker appears 
    And a text field titled "Button Text" appears 
    And tooltip text under the button text reads "Text of the button pointing to the featured content." 
    And the field is required 
    And a text field titled "Button Alt Text" appears 
    And tooltip text under the button alt text field reads "A description of the link destination for use by screen readers. Suggest using the title of the destination page.” 
```
**Analytics**

```gherkin
Scenario Click events for borderless full-width card click
Given user is viewing the AP landing page
When user clicks on a borderless full-width feature card with internal link
Then page click request is sent
And the following parameters should be captured
      | parameter | value                    |
      | event27   |                          |
      | prop4     | D=pev1                   |
      | prop8     | [language]               |
      | prop57    | [card title]             |
      | prop58    | [card title]             |
      | prop 59   | fullwidth:card position |
      | prop60    | D=pagename               |
      | prop61    | [previous page name]     |
      | prop67    | D=pagename               |
```
```gherkin
Scenario Click events for borderless full-width card click
Given user is viewing the AP landing page
When user clicks on a borderless full-width feature card with external link
And page click request is sent
Then the following parameters should be captured
Click Event:
      | parameter | value                    |
      | event27   |                          |
      | prop4     | D=pev1                   |
      | prop8     | [language]               |
      | prop57    | [card title]             |
      | prop58    | [card title]             |
      | prop 59   | fullwidth:card position |
      | prop60    | D=pagename               |
      | prop61    | [previous page name]     |
      | prop67    | D=pagename               |

Exit Link Click:
      | parameter | value           |
      | event1    |                 |
      | prop6     | [short title]   |
      | prop8     | [language]      |
      | prop10    | [browser title] |
      | prop25    | [exit date]     |
      | prop44    | [exit page tag] |
      | eVar2     | D=c8            |
      | evar7     | D=c7            |
      | evar44    | D=c44           |
```

---
### Resources
Mockups
- Desktop: https://publicis.invisionapp.com/share/DZWC0VL2B3E#/410081138_AP_Landing_Page_V9_-_Desktop

- Tablet 1024:  https://publicis.invisionapp.com/share/DZWC0VL2B3E#/415867266_AP_Landing_Page_V9_-_Tablet_1024

- Mobile: https://publicis.invisionapp.com/share/DZWC0VL2B3E#/411216125_AP_Landing_Page_V9_-_Mobile

### Notes

1x1 Crop
- Max width: 610px
- 1441: 610px
- 1440-->1025, 1024, 768: 330px
- 640: 610px
- 320: 290px

Content Manager
- _Add as paragraph to Contents_ 

### Fields
- on Home and Landing Wiki:  https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Home-&-Landing-Page#borderless-full-width-card

---

### Tasks
- [ ] Create Borderless Full-Width Card paragraph type
- [ ] Add styling
- [ ] Add analytics for card click (ACs to be added to story)

### LINKED ISSUE #2785: Augment the Landing Page Content Type
### Description

Add a new field for template theme containing "Standard" and "Special Report" options.

**Parent Issue:** #2788

### Sub-Tasks
- [ ] Add new 'Home and Landing Page Style” field
- [ ] Add template suggestions for theme based on field
- [ ] Add new scss partial, scoped to new special-report landmark
- [ ] Implement Unit Tests

### LINKED ISSUE #2794: Create a new twig template for Special Report style
Create a  new twig template for the Special Report landing page style

- [ ] Create Template
- [ ] Create styles for page options
- [ ] Add layout styles
- [ ] Create webpack entrypoint

**Parent Issue:** #2785

### PR DESCRIPTION
**Pull request by adriancofie**
## Description

ODE: http://ncigovcdode350.prod.acquia-sites.com/

----
 (#2774, #2785, #2794 )
     
- Augments the Home and Landing Page
- Adds FE templates and entrypoints
-  Updates page options display

@arcepaul
- Special Report Hero and Page Options styling
- Bugfix changes; hero image and h1 tweaks; borderless card padding
- Background texture added
----
(#2775 ) 
@erikscottmeyer 
- Added new Borderless Card paragraph type, template, associated sass, also configured and added new image style to render images 1x1.
- Borderless Card analytics

----
Closes #2774 
Closes #2785 
Closes #2794 
Closes #2775

### CODE REVIEW

**Comment by adriancofie** [comment]
- [ ] Styling for the hero and page options for tablet /mobile are off. 

- [ ] Gradient is not appearing on hero

**Comment by claireblaustein** [comment]
My test content: http://ncigovcdode350.prod.acquia-sites.com/test/claire-test-report

- the borderless card doesn't appear as a paragraph option (tested on both templates, before and after saving)
  - We haven't created a design for this paragraph type on Standard template - I believe for the moment it should only be an option within the Special Report template. 
- Mobile styling off
- Both page title and headline are displaying in English (not spanish)

image

- when translating, template options no longer show (I don't know that they should), and get some warning messages around the banner alt text

image

**Comment by blilianyu** [comment]
Height of the hero image is appearing twice as large...on desktop it should be 540px.
Screen Shot 2020-06-15 at 12 18 51 PM

On mobile, the page title (H1) should change from All Caps to Title Case and reduce in size.
Screen Shot 2020-06-15 at 12 20 25 PM

**Comment by meglake** [comment]
Testing content: http://ncigovcdode350.prod.acquia-sites.com/megs-report
**Borderless card:**
- Override image is not displaying
- Text styles look off compared to comps (@blilianyu - can you confirm?)
- White background not displaying (this might be an issue at the template level)

**Special Report Template:**
- Page title and/or hero banner are not displaying correctly (according to comps: https://publicis.invisionapp.com/share/DZWC0VL2B3E#/screens/410081138)
- White background not showing under borderless card
- White background overlayed on hero image not showing either 
- Mobile: 
-- page title on hero is not displaying correctly (see comps: https://publicis.invisionapp.com/share/DZWC0VL2B3E#/screens/411216125)
-- social icons are not displaying correctly or in the right location

**Comment by erikscottmeyer** [comment]
1. Override image is not displaying
This is working correctly; the image wasn't displaying in test content because it hadn't had cropping applied (if cropping isn't applied to an image and the image is being rendered somewhere using a cropped style, it won't appear; even though cropping is required, for a number of reasons you could find images in the system that haven't had it applied).  The solution is to edit the image, apply crops, and publish it.
2.  Text styles look off compared to comps (@blilianyu - can you confirm?)
I believe the conform to the requirements (h2 for header, description text normal
https://github.com/NCIOCPL/cgov-digital-platform/issues/2775
The comp looks like it's using an h1 for header.
3. White background not displaying (this might be an issue at the template le
I believe this is controlled by the template styling (the card background is transparent right now, so it will take on whatever the template rendering it is using).

**Comment by claireblaustein** [comment]
When looking at the mobile banner, I'm still seeing the some of the desktop attributes in inspect, including the alt text.

```
<picture>
      <source media="(max-width: 1024px)" srcset="/sites/default/files/cgov_hero_banner/2020-06/mobile-hero.jpg">
        <img src="/sites/default/files/cgov_hero/banner/2020-06/desktop-hero.jpg" width="2000" height="1000" alt="desktop hero">
```

**Comment by adriancofie** [comment]
@claireblaustein 
>       * We haven't created a design for this paragraph type on Standard template - I believe for the moment it should only be an option within the Special Report template.
> 
This would be a new pattern in terms of limiting paragraph options ( form display logic based on a field value) . I think it's worth looking into if this is something we truly want to do, and if so whether or non-special report paragraphs should be removed from the Special Report template as well.


>     * when translating, template options no longer show (I don't know that they should), and get some warning messages around the banner alt text
> 
> 
> image

@claireblaustein I don't believe we'd want the ability for the translated versions page template to differ from the main version. Is there a use case for that scenario?

Re: The alt text /translatability none of that has changed from the existing behavior.

**Comment by claireblaustein** [comment]
@adriancofie - for the disparity in template time between translations - no, I can't think of a need, just wanted to flag it in case it was an issue. My spanish doesn't hold up to fully understanding the warning messages, so if they are expected, I suppose that's fine.

For the paragraph options, I think that's a discussion to raise with the group. We would definitely need a look at the standard template to see how it would manifest. I'll raise it in Slack.

**Comment by blilianyu** [comment]
> 1. Override image is not displaying
>    This is working correctly; the image wasn't displaying in test content because it hadn't had cropping applied (if cropping isn't applied to an image and the image is being rendered somewhere using a cropped style, it won't appear; even though cropping is required, for a number of reasons you could find images in the system that haven't had it applied).  The solution is to edit the image, apply crops, and publish it.
> 2. Text styles look off compared to comps (@blilianyu - can you confirm?)
>    I believe the conform to the requirements (h2 for header, description text normal
>    #2775
>    The comp looks like it's using an h1 for header.
> 3. White background not displaying (this might be an issue at the template le
>    I believe this is controlled by the template styling (the card background is transparent right now, so it will take on whatever the template rendering it is using).

H2 styles are not consistent with comps. They should be bold and 32px. It is larger than the current templates.

The white background that contains the entire content needs to be displayed/fixed. Please look at comps.

**Comment by mworrest** [comment]
Font for the H1 is Noto Sans. It should be Montserrat.

**Comment by meglake** [comment]
### KNOWN ISSUES TO RESOLVE BEFORE SPRINT END
### Special Report Template
**General:**
- [ ] Hero gradient for H1 needs to be fixed (see comps)
- [ ] Warning messages on hero images for translations (See @claireblaustein for more details)

**Desktop/Tablet:**
- [ ] H1 style needs to be fixed:
-- Font: Montserrat Bold
-- Size: 45/50px
-- Color: #fff
-- All caps

**Mobile only:**
- [ ] H1 style needs to be fixed:
-- Font: Montserrat Bold
-- Size: 26/26px
-- Color: #fff
-- Title case

**Mobile/Tablet:**

- [ ] H1 is not overlapping image (see comp: https://publicis.invisionapp.com/share/DZWC0VL2B3E#/screens/411216125)
- [ ] Social icons not displaying correctly or in correct place  (see comp: https://publicis.invisionapp.com/share/DZWC0VL2B3E#/screens/411216125)

**Analytics:**
- [ ] Getting 2 click events firing each time I click one of the page options
- [ ] Getting 2 page loads firing when loading: http://ncigovcdode350.prod.acquia-sites.com/special-report


### Borderless Card
**Desktop/Tablet:** 

- [ ] Width and alignment not displaying proper (see comps: Desktop - https://publicis.invisionapp.com/share/DZWC0VL2B3E#/screens/410081138, Tablet - https://publicis.invisionapp.com/share/DZWC0VL2B3E#/screens/415867266
- [ ] H2 style needs to be fixed:
-- Font: Montserrat Bold
-- Size: 32/38px
-- Color: #363636
- [ ] Card Description text style needs to be fixed:
-- Font: Noto Sans Regular
-- Size: 16/26px
-- Color: #666

**Mobile only:**
- [ ] H2 style needs to be fixed:
-- Font: Montserrat Bold
-- Size: 24/25px
-- Color: #363636
- [ ] Card Description text style needs to be fixed:
-- Font: Noto Sans Regular
-- Size: 16/25px
-- Color: #666

**Analytics:**
- [ ] Getting 2 click events firing each time click on the card (title/image/button)

**Comment by kate-mashkina** [comment]
Analytics for the borderless card click is missing two props : 
- Prop57: card title
- Prop58: card title
I checked with @Andrew-Olsson - the global analytics should be passed as for the regular feature card and those mentioned above are required.
Screenshot shows the current value being passed:
Screen Shot 2020-06-17 at 10 22 05 AM

**Comment by adriancofie** [comment]
> My test content: http://ncigovcdode350.prod.acquia-sites.com/test/claire-test-report
> 
>     * the borderless card doesn't appear as a paragraph option (tested on both templates, before and after saving)
>       
>       * We haven't created a design for this paragraph type on Standard template - I believe for the moment it should only be an option within the Special Report template.
> 
>     * Mobile styling off
> 
>     * Both page title and headline are displaying in English (not spanish)
> 
> 
> image
> 
>     * when translating, template options no longer show (I don't know that they should), and get some warning messages around the banner alt text
> 
> 
> image

@claireblaustein  Re: the warning message I am only seeing  it show up once at the top of the page. The warning itself is valid, the page style field we added is only modifiable on the main translation and doesn't appear on the translated form

**Comment by blilianyu** [comment]
Desktop
- Hero image needs and X-Large breakpoint (**possible Change Request**)
- Change the width of H1 to 60% from 85% (@media only screen and (min-width: 1025px)
.specialReport h1)

Borderless Card on breakpoints 641px and more
- Padding is needed
- Width based on comps should be 925px 

screencapture-ncigovcdode350-prod-acquia-sites-research-areas-biology-ap-test-xlarge-2020-06-18-10_27_44


Page Options need to appear on the bottom at 1024px and less

screencapture-ncigovcdode350-prod-acquia-sites-research-areas-biology-ap-test-xlarge-2020-06-18-10_35_11

**Comment by SupriyaSaxena0605** [comment]
Analytics for Special Report template: value of prop42 is not being recorded for page load.

**Comment by meglake** [comment]
Noting that the latest build has been tested and all known issues have been resolved. For reference noting a few decisions made during this Sprint:
- A change request will be created to add a an X-Large breakpoint (1920px) for the hero image 
- A new story has been created to address the social icon display on tablet and mobile breakpoints (#2807)
- A new story has been created to make the standard template the default (#2809)

**Pull request merged**
