### PR TITLE
(#3742, #3840, #4127) Update features and config_update

### LINKED ISSUE #3742: Update features module to current version
### Features to be updated:
- features - upgrade from 3.12 -> 5.0.0-alpha1

### Notes:
The first D10 version came out 4/15/2023. This is [5.0-alpha1](https://www.drupal.org/project/features/releases/5.0.0-alpha1). So this is ready to update, but the maintainer is running away from it, but this maybe be a bumpy road ahead.

### LINKED ISSUE #3840: Enabler:  config_update Module Configuration Update Base
# Update Configuration Update Base

### Configuration module to be updated:
- config_update - upgrade from 1.7 --> 2.0.0-alpha2

### Notes

* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

### LINKED ISSUE #4127: There is a duplicate user.settings.yml in the cgov_site profile's config/install
The *real* `user.settings.yml` config we want to be installed is in `profiles/custom/cgov_site/modules/custom/cgov_core/config/install`. The config in cgov_core **DOES** replace what is in the database whenever the sites are updated, so all the current prod sites are using the one from config/install.  HOWEVER, there is a separate one in  `profiles/custom/cgov_site/config/install` that ends up getting installed AFTER cgov_core for new installs. That config needs to be removed because A) it is wrong, and B) it makes features show pending changes for cgov_core always after installing locally.

### PR DESCRIPTION
**Pull request by blairlearn**
features requires config_update, so we'll just do them together.

- Update features to 5.0.0-alpha1
- Update config_update to 2.0.0-alpha2

Closes #3742
Closes #3840
Closes #4127

### CODE REVIEW

**Comment by blairlearn** [comment]
[ODE 651](https://ncigovcdode651.prod.acquia-sites.com/)

**Comment by alinai** [comment]
@blairlearn , @santwuma , @KateMashkinaNIH, Regression tests (FE and CMS), Visual regression tests and manual Article creation and verification passed on ODE 651.

**Comment by alinai** [comment]
@blairl-nih , 2nd round of testing on ODE651 passed for this one. 
cc: @KateMashkinaNIH , @laurelthrash , @santwuma

**Comment by blairlearn** [comment]
`[docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/user.settings.yml](https://github.com/NCIOCPL/cgov-digital-platform/pull/4087/files#diff-f27ed642868c5312cf045f20c2a9d4a6af282af29e9b24bc09b7b8391e159f8d)` has been reverted to its prior state, everything shows up as in sync.

image

**Review by bryanpizzillo — APPROVED** [review]

**Review by bryanpizzillo — APPROVED** [review]

**Pull request merged**
