### PR TITLE
Move long description to media module

### LINKED ISSUE #1309: Infographic - Field Updates
Please make the following updates to the Infographic content type:
- the body field has a dropdown where the user can select which wysiwyg type to use. This should be the Full WYSIWYG by default (with no dropdown option) -- this might be taken care of in a larger "body" ticket

### Field Updates:

- [x]  **Short Title** field needs to be updated to only allow 100 characters
  - [x] Update Short Title tooltip to: A short version of the title. Suggest max 45 characters including spaces. [Displays in: Lists, CTHP Research Cards, social media sharing]

- [x] **Card Title** needs updated tooltip: A shortened version of the title, for use in cards and lists. If left blank, short title will display instead.

- [x]  **Browser Title** field needs to be updated to only allow 100 characters
  - [x] Update Browser Title tooltip to: A shortened version of the title. Site name is automatically appended (Browser Title – National Cancer Institute) [Displays in: internal and external search results, browser tabs. SEO best practice: max 42 characters including spaces]

- [x]  **Meta-Description** Field 
  - [x] Add the tooltip: Succinct description of the page content. [Displays in: internal and external search results. SEO best practice: Max 320 characters, most important information should be in the first 150 characters]
  - [x] Ensure this field only allows 320 characters

- [x]  **List Description** field:
  - [x] Add Tooltip: 2-3 sentence description of the page content. [Displays in: Lists on Home/Landing, Mini Landing, and Cancer Research pages. If left blank, meta description will display instead] 

- [x]  **Feature Card Description** field: 
  - [x] Update tooltip: Concise description for the page. Suggest max 75 characters. [Displays in: feature cards] 
  - [x] Allow only 255 characters
  - [x] This field should display as a single line (not multiline)

- [x] **Promotional Image** tooltip update:  Overrides Lead Image for promotional use cases (lists, cards, social media sharing)

- [x] **Posted Date** field needs tooltip update: Date the content was posted.
- [x] **Reviewed Date** field needs tooltip update: Date that the content was last reviewed by subject matter expert. 
- [x] **Updated Date** field needs tooltip update: : Date that changes were published to body text of page. 
- [x] **Date Display Mode** field:
  * Update the tooltip to: Select which date to display. [Displays on page, beneath the body text]

- [x] **Search Engine Restrictions** field needs to add tooltip: Indicate how a page should be handled by internal (sitewide search) and external (Google) search engines.

### LINKED ISSUE #1353: Images are missing longdesc
longdesc has not been implemented for cgov_image and cgov_contextual_image. The accessible text field is there, but none of the logic to add the attribute to the image nor present the text as a URL. See cgov_infographic module for logic to steal.

### PR DESCRIPTION
**Pull request by blairlearn**
Replacement for #1434 

- Moves long description route/controller to `cgov_media`. (Closes: #1361)
- Add long description to images. (Closes #1353)
- Updates multiple fields' helper text. (Closes #1309)

### CODE REVIEW

**Comment by VictoriaSunNIH** [comment]
@blairlearn  - I'm not seeing the tooltip updates on the infographic content type on the ODE.  Everything else looks good for long desc though.

**Comment by blairlearn** [comment]
Somebody updated the ticket! :-p  Reworking it now.

**Comment by blairlearn** [comment]
Dammit. This may be my fault.  The ODE was pointing at an old branch instead of the pull request!

**Comment by VictoriaSunNIH** [comment]
Looking good!  Passes IA review.  Thanks!

**Comment by blairlearn** [comment]
This is done-done with the latest from `develop`.

**Comment by blairlearn** [comment]
Done per @VictoriaSunNIH as well.

**Pull request merged**
