### PR TITLE
Remove this file.

### PR DESCRIPTION
**Pull request by adriancofie**

### CODE REVIEW

**Comment by bryanpizzillo** [comment]
Is this some sort of art installation?

**Comment by bryanpizzillo** [comment]
Ceci n'est pas une fichier.

**Comment by bryanpnih** [comment]
Maybe this is a social commentary on how to fight against file management and organization.

**Comment by BrendanBeltzNIH** [comment]
You are now talking yourself.

**Comment by adriancofie** [comment]
The art exhibit is now closed.

**Pull request closed without merging**
