### PR TITLE
Feature/embedded feature card

### PR DESCRIPTION
**Pull request by arcepaul**

### CODE REVIEW

**Comment by arcepaul** [comment]
@bryanpizzillo 
This is just to get your eyes on this.  I tried to minimize the number of changes this go around.  One question I had though, will topic feature ever show up now or will it always be an embedded entity?

**Comment by bryanpizzillo** [comment]
>This is just to get your eyes on this. I tried to minimize the number of changes this go around. One question I had though, will topic feature ever show up now or will it always be an embedded entity?

I don't follow the question exactly, so I may be incorrect in my response. On a mini-landing page (e.g. /about-nci/organization/ccct (IIRC)) you will add the feature cards through Paragraphs, not the WYSIWYG.  

There will be Articles, Blog Posts, Content Blocks on Topic Pages, and others that will have Feature Cards inserted through the WYSIWYG.

Does that answer the question?

**Comment by arcepaul** [comment]
@bryanpizzillo 
Kind of.  I think I was trying to nail down that feature cards would only be added as embedded entities, and that things like 'topic-feature' couldn't be added otherwise.

**Comment by arcepaul** [comment]
@bryanpizzillo 
I just added mobile styling.  This is now ready to go up to ODE when you're ready.

**Pull request merged**
