### PR TITLE
Feature/file media type

### LINKED ISSUE #223: Create File Media Type
This story is to create the [File](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-File) supporting media type.

**Tasks/Subtasks:**
- [ ] Add workflow transitions for file supporting media type 
- [ ] Add content author and content reviewer permissions for file supporting media type   
- [ ] Create local fields 
- [ ] Attach all fields

### PR DESCRIPTION
**Pull request by adriancofie**
Closes #223 

Adds the File media type: https://github.com/NCIOCPL/cgov-digital-platform/wiki/Media-Type-Files

### CODE REVIEW

**Comment by VictoriaSunNIH** [comment]
ODE: http://ncigovcdode47.prod.acquia-sites.com/

**Comment by VictoriaSunNIH** [comment]
@adriancofie  - Please update the max file size...the error message says its currently 250 bytes.

**Comment by adriancofie** [comment]
http://ncigovcdode47.prod.acquia-sites.com/

**Comment by VictoriaSunNIH** [comment]
@adriancofie, @lburack  - a couple of things I'm noticing:
1. All 3 dates (posted, updated, reviewed) on the content type should default to today (they're currently blank)
2. Date display mode is not a required field.  Also, these should be a series of checkboxes that allow multi-select, and not radio button options.

**Comment by adriancofie** [comment]
@VictoriaSunNIH  Should be ready to test with updates dates / site section.

**Comment by VictoriaSunNIH** [comment]
@adriancofie - I'm testing as an editor role, and I can't actually load the site sections.  I get this error message: "You are not authorized to access this page."

Same with the author role.  Admin role works fine...

**Comment by adriancofie** [comment]
Roles / Permissions are being handled separately by BP

**Comment by VictoriaSunNIH** [comment]
Ignoring the existing issue for all media items where it's not pulling in the site section/pretty URL as the URL of the media item (which is in a separate ticket #936 ) , and the styling of the front-end of the file (which I have now opened as a separate ticket) - I think this is working as designed.  Tagging @lburack for review.

**Comment by lburack** [comment]
yup @VictoriaSunNIH  @adriancofie  - aside from the site section/pretty URL and front-end styling issues mentioned above, this is working as designed. Marking as Passed IA Review!

**Comment by adriancofie** [comment]
@bryanpizzillo  can you merge this?

**Pull request merged**
