### PR TITLE
Resolve all deprecated code warnings

### LINKED ISSUE #2918: Re-enable Deprecation Checking & Fix Issues
As part of the Drupal 8.9 upgrade we had to disable BLT's deprecated code checking because we were unable to fix the deprecation notices in app_module due to how the core maintainers implemented changes to path_alias. This task is to turn back on the Deprecation checking and fix the deprecation notices.

### Notes
TL;DR; Once we resolve all the deprecation issues we need to turn back on deprecation checking.

Issue #2927 will be updating the check that is done as part of the deprecation validation. We will be adding a new section to disable until we fix all the issues in #3127.  Additionally, in the 8.9 upgrade we added the following, however it looks like the deprecated checks may have been removed in newer BLT versions.

`<repo_root>/blt/ci.blt.yml`
```
disable-targets:
  tests:
    deprecated:
      modules: true
```

**Related Issue:** #2905

### LINKED ISSUE #3106: Deprecation Notice: Cgov Blog
### Issue description

Deprecated code warnings: cgov_site/modules/custom/cgov_blog/src/Services/BlogManager.php

```
  88     Parameter $alias_manager of method                                 
         Drupal\cgov_blog\Services\BlogManager::__construct() has typehint  
         with deprecated interface Drupal\Core\Path\AliasManagerInterface:  
         in drupal:8.8.0 and is removed from drupal:9.0.0.                  
         Use \Drupal\path_alias\AliasManagerInterface.                      
  88     Parameter $entity_query of method                                  
         Drupal\cgov_blog\Services\BlogManager::__construct() has typehint  
         with deprecated class Drupal\Core\Entity\Query\QueryFactory:       
         in drupal:8.3.0 and is removed from drupal:9.0.0. Use              
         \Drupal\Core\Entity\EntityStorageInterface::getQuery() or          
         \Drupal\Core\Entity\EntityStorageInterface::getAggregateQuery()    
         instead.       
```

> **ESTIMATE** TBD

### LINKED ISSUE #3107: Deprecation Notice: Cgov Core Module
### Issue description

**Deprecated code warnings: cgov_site/modules/custom/cgov_core/cgov_core.module**

```
  80     Call to deprecated function entity_load():                            
         in drupal:8.0.0 and is removed from drupal:9.0.0. Use the             
         entity type storage's load() method.                                  
  90     Call to deprecated function drupal_set_message():                     
         in drupal:8.5.0 and is removed from drupal:9.0.0.                     
         Use \Drupal\Core\Messenger\MessengerInterface::addMessage() instead.  
```

**Deprecated code warnings: cgov_site/modules/custom/cgov_core/src/Services/CgovNavigationManager.php**

```
  120    Parameter $pathAliasManager of method                                      
         Drupal\cgov_core\Services\CgovNavigationManager::__construct() has         
         typehint with deprecated interface                                         
         Drupal\Core\Path\AliasManagerInterface:                                    
         in drupal:8.8.0 and is removed from drupal:9.0.0.                          
         Use \Drupal\path_alias\AliasManagerInterface.     
```

**Deprecated code warnings: cgov_site/modules/custom/cgov_core/src/Plugin/PathProcessor/UrlProcessor.php**
```
  56     Parameter $aliasManager of method                                             
         Drupal\cgov_core\Plugin\PathProcessor\UrlProcessor::__construct() has         
         typehint with deprecated interface                                            
         Drupal\Core\Path\AliasManagerInterface:                                       
         in drupal:8.8.0 and is removed from drupal:9.0.0.                             
         Use \Drupal\path_alias\AliasManagerInterface.   
```

> **ESTIMATE** TBD

### LINKED ISSUE #3108: Deprecation Notice: Cgov Syndication
### Issue description

Deprecated code warnings: 

```
 ------ ---------------------------------------------------------------------- 
  Line   cgov_syndication.module                                               
 ------ ---------------------------------------------------------------------- 
  64     Call to deprecated function entity_load():                            
         in drupal:8.0.0 and is removed from drupal:9.0.0. Use the             
         entity type storage's load() method.                                  
  74     Call to deprecated function drupal_set_message():                     
         in drupal:8.5.0 and is removed from drupal:9.0.0.                     
         Use \Drupal\Core\Messenger\MessengerInterface::addMessage() instead.  
 ------ ----------------------------------------------------------------------     
```

> **ESTIMATE** TBD

### LINKED ISSUE #3109: Deprecation Notice: Cgov Site Section
### Issue description

Deprecated code warnings: cgov_site/modules/custom/cgov_site_section/src/Plugin/Validation/Constraint/UniqueCgovUrlConstraintValidator.php

```
  32     Call to deprecated method getStorage() of class                                                                   
         Drupal\Core\Entity\EntityManager:                                                                                 
         in drupal:8.0.0 and is removed from drupal:9.0.0.                                                                 
         Use \Drupal\Core\Entity\EntityTypeManagerInterface::getStorage()                                                  
         instead.      
```

> **ESTIMATE** TBD**

### LINKED ISSUE #3110: Deprecation Notice: Cgov Event
### Issue description

Deprecated code warnings: cgov_site/modules/custom/cgov_event/src/Controller/ICalendarController.php

```
  51     Call to deprecated method getStorage() of class                             
         Drupal\Core\Entity\EntityManager:                                           
         in drupal:8.0.0 and is removed from drupal:9.0.0.                           
         Use \Drupal\Core\Entity\EntityTypeManagerInterface::getStorage()            
         instead.                                                                    
  111    Call to deprecated constant FILE_EXISTS_REPLACE: Deprecated in              
         drupal:8.7.0 and is removed from drupal:9.0.0. Use                          
         \Drupal\Core\File\FileSystemInterface::EXISTS_REPLACE.     
```

> **ESTIMATE** TBD

### LINKED ISSUE #3111: Deprecation Notice: Cgov Migration
### Issue description

Deprecated code warnings: cgov_site/modules/custom/cgov_migration/cgov_migration.install

```
  14     Call to deprecated function db_select():                             
         in drupal:8.0.0 and is removed from drupal:9.0.0. Instead, get       
         a database connection injected into your service from the container  
         and                                                                  
         call select() on it. For example,                                    
  16     Call to deprecated function db_like():                               
         in drupal:8.0.0 and is removed from drupal:9.0.0. Instead,           
         get a database connection injected into your service from the        
         container                                                            
         and call escapeLike() on it. For example,     <NOTE: This error was just truncated.>
```

> **ESTIMATE** TBD

### LINKED ISSUE #3112: Deprecation Notice: Cgov Redirect Manager
### Issue description

**Deprecated code warnings: cgov_site/modules/custom/cgov_redirect_manager/src/CgovImporterService.php**

```
  84     Call to deprecated function drupal_set_message():                           
         in drupal:8.5.0 and is removed from drupal:9.0.0.                           
         Use \Drupal\Core\Messenger\MessengerInterface::addMessage() instead.        
  89     Call to deprecated function drupal_set_message():                           
         in drupal:8.5.0 and is removed from drupal:9.0.0.                           
         Use \Drupal\Core\Messenger\MessengerInterface::addMessage() instead.        
  102    Call to deprecated function drupal_set_message():                           
         in drupal:8.5.0 and is removed from drupal:9.0.0.                           
         Use \Drupal\Core\Messenger\MessengerInterface::addMessage() instead.        
  115    Call to deprecated function drupal_set_message():                           
         in drupal:8.5.0 and is removed from drupal:9.0.0.                           
         Use \Drupal\Core\Messenger\MessengerInterface::addMessage() instead.        
  216    Call to deprecated function drupal_set_message():                           
         in drupal:8.5.0 and is removed from drupal:9.0.0.                           
         Use \Drupal\Core\Messenger\MessengerInterface::addMessage() instead.        
  473    Call to deprecated method entityManager() of class Drupal:                  
         in drupal:8.0.0 and is removed from drupal:9.0.0.                           
         Use \Drupal::entityTypeManager() instead in most cases. If the needed       
         method is not on \Drupal\Core\Entity\EntityTypeManagerInterface, see        
         the                                                                         
         deprecated \Drupal\Core\Entity\EntityManager to find the                    
         correct interface or service.      
```

**Deprecated code warnings: cgov_site/modules/custom/cgov_redirect_manager/src/Form/RedirectImport.php **

```
  121    Call to deprecated function drupal_set_message():                           
         in drupal:8.5.0 and is removed from drupal:9.0.0.                           
         Use \Drupal\Core\Messenger\MessengerInterface::addMessage() instead.        
  126    Call to deprecated function drupal_set_message():                           
         in drupal:8.5.0 and is removed from drupal:9.0.0.                           
         Use \Drupal\Core\Messenger\MessengerInterface::addMessage() instead. 
```

> **ESTIMATE** TBD

### LINKED ISSUE #3113: Deprecation Notice: Cgov Vocab Manager
### Issue description

Deprecated code warnings: cgov_site/modules/custom/cgov_vocab_manager/src/Manager/CgovVocabManager.php

```
  46     Call to deprecated method getVocabularyId() of class                          
         Drupal\taxonomy\TermInterface:                                                
         in drupal:8.?.? and is removed from drupal:9.0.0. Use                         
         TermInterface::bundle() instead.                      
```

> **ESTIMATE** TBD

### LINKED ISSUE #3114: Deprecation Notice: Cgov Yaml Content
### Issue description

Deprecated code warnings: cgov_site/modules/custom/cgov_yaml_content/src/Service/CgovYamlContentEventSubscriber.php

```
  82     Parameter $entityQueryFactory of method                                                    
         Drupal\cgov_yaml_content\Service\CgovYamlContentEventSubscriber::__co                      
         nstruct() has typehint with deprecated class                                               
         Drupal\Core\Entity\Query\QueryFactory:                                                     
         in drupal:8.3.0 and is removed from drupal:9.0.0. Use                                      
         \Drupal\Core\Entity\EntityStorageInterface::getQuery() or                                  
         \Drupal\Core\Entity\EntityStorageInterface::getAggregateQuery()                            
         instead.                                                                                   
  260    Call to deprecated constant FILE_CREATE_DIRECTORY: Deprecated in                           
         drupal:8.7.0 and is removed from drupal:9.0.0. Use                                         
         \Drupal\Core\File\FileSystemInterface::CREATE_DIRECTORY.                                   
  260    Call to deprecated function file_prepare_directory():                                      
         in drupal:8.7.0 and is removed from drupal:9.0.0.                                          
         Use \Drupal\Core\File\FileSystemInterface::prepareDirectory().                             
  263    Call to deprecated constant FILE_EXISTS_REPLACE: Deprecated in                             
         drupal:8.7.0 and is removed from drupal:9.0.0. Use                                         
         \Drupal\Core\File\FileSystemInterface::EXISTS_REPLACE.      
```

> **ESTIMATE** TBD

### LINKED ISSUE #3115: Deprecation Notice: Cgov Site (Profile code)
### Issue description

Deprecated code warnings: cgov_site/src/Form/CgovAlterForm.php

```
  56     Call to deprecated function drupal_set_message():                     
         in drupal:8.5.0 and is removed from drupal:9.0.0.                     
         Use \Drupal\Core\Messenger\MessengerInterface::addMessage() instead.  
```

> **ESTIMATE** TBD

### LINKED ISSUE #3116: Deprecation Notice: App Module
### Issue description

Deprecated code warnings: app_module/src/AppPathManager.php     

```
  98     Parameter $alias_manager of method                                     
         Drupal\app_module\AppPathManager::__construct() has typehint with      
         deprecated interface Drupal\Core\Path\AliasManagerInterface:           
         in drupal:8.8.0 and is removed from drupal:9.0.0.                      
         Use \Drupal\path_alias\AliasManagerInterface.                          
  98     Parameter $alias_storage of method                                     
         Drupal\app_module\AppPathManager::__construct() has typehint with      
         deprecated interface Drupal\Core\Path\AliasStorageInterface:           
         \Drupal\Core\Path\AliasStorage is deprecated in drupal:8.8.0 and       
         is removed from drupal:9.0.0. Use the "path_alias.repository" service  
         instead, or the entity storage handler for the "path_alias" entity     
         type                                                                   
         for CRUD methods.      
```

> **ESTIMATE** TBD

### PR DESCRIPTION
**Pull request by bryanpizzillo**
This resolves all deprecation notices.
ODE: https://ncigovcdode428.prod.acquia-sites.com/

Closes #3116
Closes #3106 
Closes #3107 
Closes #3114
Closes #3111 

Closes #3108
Closes #3109
Closes #3110 
Closes #3112 
Closes #3113 
Closes #3115 
 
Closes #2918

### CODE REVIEW

**Comment by kate-mashkina** [comment]
Automated regression tests have passed

**Comment by kate-mashkina** [comment]
[ ] #3116
[ ] #3106 
[ ] #3107 
[ ] #3114
[ ] #3111 

[ ] #3108
[ ] #3109
[ ] #3110 
[ ] #3112 
[ ] #3113 
[ ] #3115 
 [ ] #2918

**Comment by kate-mashkina** [comment]
Redirect Manager #3112
Uploaded empty .cvs - no recent log message entry... But neither did the dev-acs logs reflect upload 
Cgov Site Section #3109 - logged a bug for existing issue https://github.com/NCIOCPL/cgov-digital-platform/issues/3170, not the issue related to this PR

**Comment by alinai** [comment]
Noticed the following issues while testing  #3116: 

1. On clicking each letter of the A-Z list or on loading Dict .of Cancer Terms  , we see the following on the console. It happens on ODE 428 and dev-ac as well.

image

2. Noticed one deprecation warning on the Dict. of Cancer Terms console when the survey popped up on Prod. Wanted to verify if need to worry about it as we are handling all deprecate messages in this ticket and I could not verify surveys on ODE.

image

3. Trying to Print CTS results from the following search results page returns error message on ODE as well as Prod
https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/r?a=90&loc=0&rl=1&t=C3992

image

**Comment by kate-mashkina** [comment]
redirects seems to be working, funky, but working. The redirect instructions had also been updated here https://github.com/NCIOCPL/cgov-digital-platform/wiki/Redirects

**Pull request merged**
