### PR TITLE
(#2382) Add ajax callback for updating blog topics related to blog se…

### PR DESCRIPTION
**Pull request by kalidindir**
…ries

### CODE REVIEW

**Comment by kalidindir** [comment]
closes (#2382 )

**Comment by lburack** [comment]
Hi @kalidindir — can you remove the tooltip text? It's not necessary as this is pretty self explanatory. 
> Blog topics (categories) vocabulary items. Limited to this blog post's series only.

Otherwise, two scenarios aren't working as expected:

### Scenario 1
User translates a blog post that is associated with a blog series that has blog categories/topics.
#### Acceptance Criteria:
- The list of available categories/topics should appear in the Drupal form. 
#### What's Happening on the ODE:
- When I translate a blog post, the Blog Topics section doesn't display any categories (screenshot below). If I change the blog series dropdown and then change it back to the Spanish blog series, the categories then appear.
Screen Shot 2019-10-24 at 5 36 17 PM

### Scenario 2
An English blog post which is tagged to one or more categories is translated into Spanish. 
>_**NOTE:**_ this scenario assumes the English categories are translated into Spanish.
#### Acceptance Criteria:
- The categories (or categories) are automatically selected in the translated Drupal form.

**Comment by kalidindir** [comment]
> Hi @kalidindir — can you remove the tooltip text? It's not necessary as this is pretty self explanatory.
Should i remove the entire tooltip?

**Comment by kalidindir** [comment]
@lburack @VictoriaSunNIH 
deployed fix on ODE.

**Comment by lburack** [comment]
Passed scenarios listed above (https://github.com/NCIOCPL/cgov-digital-platform/pull/2504#issuecomment-546120757). 
@kalidindir, @VictoriaSunNIH  — marking this as Passed IA Review. Needs QA Review before getting merged in @dragostiny @alinai @SupriyaSaxena0605

**Pull request merged**
