### PR TITLE
(#1817, #1799) Content Heading tooltip; Selected References heading translation

### PR DESCRIPTION
**Pull request by sarinapadilla**
* Add tooltip to clarify use for field
* Closes NCIOCPL#1817

* Add translation for Selected Reference/References
* Closes NCIOCPL#1799

### CODE REVIEW

**Comment by bryanpizzillo** [comment]
ODE: http://ncigovcdode163.prod.acquia-sites.com/AH_VIEW

**Comment by VictoriaSunNIH** [comment]
Looks good.  Passes IA review!

**Comment by lburack** [comment]
it seems the tooltip isn't there anymore. This is a screenshot of a mini landing from ODE 163:
Screen Shot 2019-06-03 at 1 39 30 PM

**Comment by VictoriaSunNIH** [comment]
@lburack  - this isn't on the ODE because the ODE was repurposed.

**Pull request closed without merging**
