### PR TITLE
Event - Add to Outlook Calendar link

### PR DESCRIPTION
**Pull request by sarinapadilla**

### CODE REVIEW

**Comment by VictoriaSunNIH** [comment]
The outlook link should appear below the address (see comp https://lm1a12.axshare.com/#g=1&p=event_page)

**Comment by sarinapadilla** [comment]
The location of the outlook link is fixed: http://ncigovcdode71.prod.acquia-sites.com

**Comment by VictoriaSunNIH** [comment]
Looks good!

**Comment by VictoriaSunNIH** [comment]
Looking good! Marking as passed.  Thanks @sarinapadilla !

**Pull request merged**
