### PR TITLE
Feature/prevnext

### LINKED ISSUE #349: Older/Newer Post (Previous/Next) Links (on the Blog Post)
This story is to implement Older Post/Newer Post links. These appear at the bottom of blog posts, above Recommended Content:
image

**"< Older Post" link:**
  * The system should not display this link when the blog post is the oldest post available for the series (as determined by the post date)
* The system shall display the Page Title of the Older Post beneath the Older Post link
* For Spanish pages, the "Older Post" link should display as "< Artículo anterior"

**"Newer Post >" link:**
* The system should not display this link when the blog post is the newest post available for the series (as determined by the post date)
* The system shall display the Page Title of the Newer Post beneath the Newer Post link
* For Spanish pages, the "Newer Post" link should display as "Artículo siguiente >"

### LINKED ISSUE #697: Older Posts/Newer Posts Links on Blog Landing Page
This story is to implement Older Posts/Newer Posts links on the blog series/landing page. These appear at the bottom of blog series, above the footer. 

**"< Older Posts" link:**
  * The system should not display this link when the blog landing page displays the oldest set of blog posts available for the series (as determined by the post date)
* For Spanish pages, the "Older Posts" link should display as "< Artículos anteriores"

**"Newer Post >" link:**
* The system should not display this link when the blog landing page displays the newest set of blog posts available for the series (as determined by the post date)
* For Spanish pages, the "Newer Post" link should display as "Artículos siguientes > "

### PR DESCRIPTION
**Pull request by daquinohd**
* Added prev/next logic; built out html; added series filter logic; rearranged test content 
* Merge "origin/feature/blog-nav" into feature/blog-series-pagination (#914)
* Removed hardcoded HTML for blog post pagination
* Fixed configs for page_manager, translations
* Added BlogPager.php & dummy php plugins
* Added service yml for cgov_blog module
* Added custom mini pager template
(closes #349)
(closes #697)

### CODE REVIEW

**Comment by daquinohd** [comment]
@VictoriaSunNIH @lburack - this is a re-submit of the Prev/Next/Older/Newer links pull request. Translation is in place; styling is not.

**Comment by daquinohd** [comment]
This is in place on http://ncigovcdode50.prod.acquia-sites.com/

**Comment by lburack** [comment]
This working as expect on English, but there are issues with Spanish (pagination first displays in Spanish, but then morphs into English). I logged #1071. Marking this as Does Not Pass IA Review. Let us know when we can test again!

**Comment by daquinohd** [comment]
Will resubmit PR as part of "feature/blogs" branch.

**Pull request closed without merging**
