### PR TITLE
Implement / Update Site Section URL for Media.

### LINKED ISSUE #936: Implement and or Apply Site Section Validation for Non-Node Entities (Media)
## Description 

Site Section validation currently only applies to entities which are nodes. Some media items have a site section and therefore require said validation.

Implement the validation and / or modify and apply the existing validation.

This should also include updating the URL of the media item to be the pretty URL set on the item (or to follow the URL rules for site sections if no pretty URL is set)

### LINKED ISSUE #969: Videos - URL/Site Section not working as expected
I created a video and selected the site section, but the video is not being placed in that site section. The left side of the video page is just blank. The URL is also not correct — not picking up the site section or appending the pretty URL I entered.

These will soon get blown away, but FWIW now, here are the videos I created:
http://ncigovcddev.prod.acquia-sites.com/video/101
http://ncigovcddev.prod.acquia-sites.com/video/106

### PR DESCRIPTION
**Pull request by adriancofie**
Adds Cgov URLs for media items (File, Video).

Closes #936 - Add Site Section for Non-Node Entities
Close #969 - Video -- URL /Site Section not working as expected

### CODE REVIEW

**Comment by adriancofie** [comment]
ODE: http://ncigovcdode75.prod.acquia-sites.com/

**Comment by lburack** [comment]
@adriancofie - I'm trying to add a new video. When I click the Select Site Section button, I see the please wait timer flash for a second and then disappear; the site section browser then does not appear as expected. 

The site section browser does appear when I try to add a file though. 
In testing the file, I'm getting an unexpected error with the pretty URL. Almost all of the PDFs on cancer.gov end with .pdf; this is necessary for analytics tracking. I used [this PDF](https://www.cancer.gov/publications/patient-education/children-with-cancer.pdf) as a test case, with the pretty URL being _children-with-cancer.pdf_. When I tried to save, I got this error: The Pretty URL field only accepts letters, numbers, and dashes.

**Comment by VictoriaSunNIH** [comment]
@adriancofie , @lburack , @bryanpizzillo - this can be marked as passed, but there is still an outstanding issue where we can't open the site section browser until a URL is put into the youtube URL field. (https://github.com/NCIOCPL/cgov-digital-platform/issues/1033) which is a larger issue with not being able to change site sections.

**Comment by adriancofie** [comment]
Changing the tag per comment.

**Pull request merged**
