### PR TITLE
(#1198) Drop duplicates from press release rss feed

### LINKED ISSUE #1198: Drop revision table from press_release_rss view
If an English Press Release node has a Spanish translation with a different Posted_Date value, a duplicate record appears in the English Press Release feed.

Followup on #298.

### LINKED ISSUE #1712: Use content posted date for press_releases view filter
The view currently filters by the revision posted date, which results in duplicate rows in the view.

### LINKED ISSUE #1713: Use content posted date for blog_rss view filter
The view currently filters by the revision posted date, which results in duplicate rows in the view.

### PR DESCRIPTION
**Pull request by bkline**
Closes #1198 
Closes #1712 
Closes #1713 

Uses the content posted date instead of the content revision posted date.

### CODE REVIEW

**Comment by bryanpizzillo** [comment]
I created an English release and made the date 5/13/2019. Then I translated and set the translation to 5/14/2019.

It appears that this duplication is not only for RSS feeds.

On the home page listing
URL: https://www-dev-ac.cancer.gov/espanol/noticias 
Screen Shot 2019-05-13 at 9 55 05 PM

Also on listing pages:
URL: https://www-dev-ac.cancer.gov/espanol/noticias/comunicados-de-prensa/2019
Screen Shot 2019-05-13 at 9 56 20 PM

**Comment by VictoriaSunNIH** [comment]
ODE: http://ncigovcdode138.prod.acquia-sites.com

**Comment by VictoriaSunNIH** [comment]
#1713 does not pass IA review - when I try to view a blog RSS feed, the website returns " The website encountered an unexpected error. Please try again later."

**Comment by bkline** [comment]
@VictoriaSunNIH - I am unable to reproduce the behavior in my local instance (though I see it myself in the ODE). I have reached out to @bryanpizzillo for help. (See thread in `digital_platform_dev` channel.)

**Comment by VictoriaSunNIH** [comment]
Looking good!  I'll do a quick recheck once this gets to dev since it seemed to not work the first time, but refreshing the ODE made it work...

**Pull request closed without merging**
