### PR TITLE
Ticket/425 citations common field

### PR DESCRIPTION
**Pull request by sarinapadilla**

### CODE REVIEW

**Comment by VictoriaSunNIH** [comment]
@lburack - test citations here: http://ncigovcdode41.prod.acquia-sites.com/

**Comment by lburack** [comment]
This does NOT pass my IA review :( The implementation of the Citations is really nice and easy to use, but all of the headings are wrong on the front-end:
- Blog Post and Article display the heading above the citations as "Selected Resources". This should be "Selected References" (see live C.gov page: https://www.cancer.gov/about-cancer/treatment/types/immunotherapy/bio-therapies-fact-sheet
  - http://ncigovcdode41.prod.acquia-sites.com/research/lbb-article-citation
  - http://ncigovcdode41.prod.acquia-sites.com/about-cancer/lbb-blog-citation
- Press Releases have the heading "Resources" but this should be "References" 
  - [live Cgov press release](https://www.cancer.gov/news-events/press-releases/2019/BRCA-exchange) VERSUS http://ncigovcdode41.prod.acquia-sites.com/about-cancer/understanding/citations-press-release

**Comment by VictoriaSunNIH** [comment]
@lburack - I took a look and the labels look to have been updated.  Tagging you to confirm before we pass this one.

**Comment by lburack** [comment]
Everything looks good to me! Labels are correctly displayed on all content types and for both singular and plural!

**Pull request merged**
