### PR TITLE
(NCIOCPL#1678) Browser title is missing from Drug Info Summaries

### PR DESCRIPTION
**Pull request by blairlearn**
- Add field_browser_title to Drug Info Summaries.
- Load field_browser_title via the API.
- Add hook_field_widget_form_alter to control body field's input format.
- Connect field_meta_tags and field_pdq_url to forms/views.

Closes: #1678

### CODE REVIEW

**Comment by VictoriaSunNIH** [comment]
ODE: http://ncigovcdode145.prod.acquia-sites.com/

**Comment by blairlearn** [comment]
Comments added to reflect meta_tags, pdq_url being added to the fields.

**Comment by VictoriaSunNIH** [comment]
Checked the browser title, as well as the page metadata and I'm seeing the browser title value.  Passes IA review!

**Comment by lburack** [comment]
STRONG WORK! Passes IA Review!

**Pull request closed without merging**
