### PR TITLE
(#3814) Factbook High Chart Mobile Breakpoint Issues

### LINKED ISSUE #3814: Factbook High Chart Mobile Breakpoint Issues
**Description:** 

During manual testing for the initial Factbook enhancement updates (#3761), the below issues was identified. At mobile breakpoint for the "Research Career Awards 'K' Program," : 
1. the legend text is centered and thus legend text wraps (see screen shot)
2. title of the chart overlaps with the mobile menu (see screen shot)

At the time of testing, these issues were not occurring in production. Determined that these issues were not substantial enough to prevent release of #3761. Creating this ticket to retroactively address these two issues. 

Prod URL: https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/k-awards

**Steps to reproduce:** 
1. Navigate to the "Research Career Awards 'K' Program," chart in production (link above)
2. Reduce to mobile breakpoint
3. See two issues mentioned above

**Screenshots of issue:** 
image
image
image

### PR DESCRIPTION
**Pull request by seyilonge-nci**
Closes #3814

* Added styling for context menu button to reduce overlap on title

### CODE REVIEW

**Review by blairlearn — APPROVED** [review]

**Comment by alinai** [comment]
The chart appears bigger at mobile breakpoint compared tp Prod. @seyilonge-nci is looking into it.
cc: @KateMashkinaNIH , @blairl-nih , @jfrank-nih , @santwuma , @laurelthrash

**Comment by seyilonge-nci** [comment]
> The chart appears bigger at mobile breakpoint compared to Prod. @seyilonge-nci is looking into it. cc: @KateMashkinaNIH , @blairl-nih , @jfrank-nih , @santwuma , @laurelthrash

@alinai This is due to the legend text no longer wrapping which results in a larger legend width that is the same as the container for the pie chart. It's responsive, and meant to be this way.

**Comment by alinai** [comment]
We got 15 failures in Visual regressions and they are mostly at mobile breakpoints. The charts are looking weird at mobile breakpoints in emulators and real devices.
cc: @seyilonge-nci , @santwuma , @laurelthrash , @blairl-nih

**Comment by seyilonge-nci** [comment]
@blairlearn Please can you review again. I missed specificity for the K-Awards pie chart earlier.

**Review by blairlearn — APPROVED** [review]

**Comment by seyilonge-nci** [comment]
> We got 15 failures in Visual regressions and they are mostly at mobile breakpoints. The charts are looking weird at mobile breakpoints in emulators and real devices. cc: @seyilonge-nci , @santwuma , @laurelthrash , @blairl-nih

@alinai Issue has been fixed. Will let you know it's on an ODE for re-testing.

**Comment by alinai** [comment]
Looks good on ODE. Confirmed with @santwuma and @laurelthrash.

**Pull request merged**
