### PR TITLE
(#3062) same site section at root should not get created

### LINKED ISSUE #3062: A new site section should not be able to be created at the root
### Issue description
A new site section should never be allowed to be created at the root - as this breaks our cancer.gov homepage. 

We need to block this from happening.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  A new site section is created and the landing page was set, with everything checked to hide in navigation. 
2. The parent page (in the Relations drop down) was not selected. 
3. Because there was no URL path,  the site section was added to the root
4. This caused our main homepage (cancer.gov) to not render and show a page not found status.

### What's the expected result?
-We need to make sure that a new site section is not able to be created at the root, and that a relations is set for any new site section that is not the root.

### What's the actual result?
- breakage of cancer.gov

### Additional details / screenshot
- Screenshot

### Related Tickets
* Issue #9999
* Issue #9999

### PR DESCRIPTION
**Pull request by navsunka**
ODE: https://ncigovcdode744.prod.acquia-sites.com/

Closes #3062

### CODE REVIEW

**Review by bryanpizzillo — COMMENTED** [review]
IDK how this was actually tested, but I enabled Greek on the ODE and *was* able to create a new root term. (Which is correct) 

This use case simulates when we would create a new Spanish root, which IIRC, is part of the process of making a site support Spanish.

IDK if @lburack looked at this, but the error message did not make much sense. If I try and create a duplicate, then "The site section cannot be saved. Please set the parent site section under the Relations tab." shows. But I do have a parent set, it just happens to be `<root>`.

We should be noting that you cannot have more than 1 site section in the same language at the root.

**Comment by lburack** [comment]
I did not review the error message. I suggest the following instead: 

> The site section cannot be saved. There is already a site section at the root (the homepage). Please update the parent site section under the Relations tab.

@andyvanavery31 @bryanpizzillo @navsunka

**Comment by KateMashkinaNIH** [comment]
> IDK how this was actually tested, but I enabled Greek on the ODE and was able to create a new root term. (Which is correct)
@bryanpizzillo since we are not supposed to use admin user for testing purposes, I did a workaround of editing Spanish root and moving it one level down in the relations tree, effectively getting rid of existing spanish root and then proceeding with new root creation, same thing with english ( and then simply moving them back to root to restore original site sections relations after deleting test roots) 

ODE functions according to acceptance criteria ( plus I verified that user IS able to select all 3 Navigation Display Options) 
Also Regression tests pass

**Comment by bryanpizzillo** [comment]
> > IDK how this was actually tested, but I enabled Greek on the ODE and was able to create a new root term. (Which is correct)
> > @bryanpizzillo since we are not supposed to use admin user for testing purposes, I did a workaround of editing Spanish root and moving it one level down in the relations tree, effectively getting rid of existing spanish root and then proceeding with new root creation, same thing with english ( and then simply moving them back to root to restore original site sections relations after deleting test roots)
> 
> ODE functions according to acceptance criteria ( plus I verified that user IS able to select all 3 Navigation Display Options) Also Regression tests pass

This was more about how to test that you *could* create a new top level node in another language. But I guess the method you could use worked. I assume you mean by "moving it down" was to move Spanish to under English.

**Review by bryanpizzillo — APPROVED** [review]

**Pull request merged**
