### PR TITLE
(#4028) fix PDQ deprecation notices

### LINKED ISSUE #4028: Fix PHPStan deprecation notices in PDQ Modules.
There are a number of deprecation calls in the PDQ modules.
* pdq_cancer_information_summary/pdq_cancer_information_summary.module
* pdq_cancer_information_summary/tests/src/Functional/ApiTest.php
* pdq_core/src/Commands/RevisionPrunerCommands.php
* pdq_core/src/Plugin/rest/resource/PDQResource.php
* pdq_glossifier/src/Plugin/CKEditorPlugin/CgovGlossifier.php

## Tasks:
- [x] Edit `{repo.root}/phpstan.neon` and remove the above files from the `excludePaths` element.
- [x] Edit `{repo.root}/phpcs.xml` and remove the `CgovGlossifier.php` `<exclude-pattern>` entry
   * PLEASE do not remove the .js files, stupid PHPCS autocorrects `true` to `TRUE`.
- [x] Run `blt validate:phpcs` and `blt validate:phpstan` and fix the listed issues.

> **Note**
> There will probably be other PHPStan issues. Shout when you hit any that don't make sense. 
>
> What won't make sense? things like "Access to an undefined property <SOME_CLASS>::moderation_state". There are various ways to help PHPStand understand the type hinting. 
>
> You can always add a conditional of `if (!($entity instanceof NodeInterface)) { throw new \Exception('bad mojo'); }`, but if your `@returns` comment for a function says the type is `EntityInterface`, and it will always a `NodeInterface`, change it to `NodeInterface`.
>
> (e.g., `$entity->getTranslatedContent()` always returns `ContentEntityInterface` and you will HAVE to check `instanceof NodeInterface` before checking `$entity->moderation_state`.)

### PR DESCRIPTION
**Pull request by bryanpizzillo**
- removed suppression of checks for PDQ files
- resolved the problems identified by phpcs and phpstan

Closes #4028

### CODE REVIEW

**Comment by santwuma** [comment]
Testing notes:
Glossification of article page

**Comment by SupriyaSaxena0605** [comment]
@bryanpizzillo @bkline 
 Automation tests passed on ODE623. Completed the manually verification of failed tests.
@bkline please upload the PDQs.

**Comment by alinai** [comment]
@bryanpizzillo , @santwuma , @bkline , 
On ODE#625,
1. Created an article and verified that glossification works as expected for an article:
Test url:  https://ncigovcdode625.prod.acquia-sites.com/about-cancer/coping/feelings/test-article-glossification
Test url: https://ncigovcdode625.prod.acquia-sites.com/espanol/cancer/sobrellevar/sentimientos/test-article-glossification-sp
 
2. Verified that glossification works as expected on PDQ Cancer Information Summary
Test url: https://ncigovcdode625.prod.acquia-sites.com/types/breast/patient/breast-treatment-pdq
Test url: https://ncigovcdode625.prod.acquia-sites.com/espanol/tipos/seno/paciente/tratamiento-seno-pdq

3. Verified that glossification works as expected on PDQ Drug Information Summary
Test url: https://ncigovcdode625.prod.acquia-sites.com/about-cancer/treatment/drugs/bevacizumab

@bkline, @bryanpizzillo , @santwuma ,  On ODE#625 I was seeing an error in the console when I first started adding glossified term to the WYSIWYG of an article. After I published the page I did not see the error. When I was editing the content and added some more glossified term, did not see the error anymore. The discussion and screenshots about error are in the Digital Platform (DP) channel. 

I also created an article just now but did not see the error anymore: 
https://ncigovcdode625.prod.acquia-sites.com/about-cancer/coping/feelings/test-and-test-article-glossification
https://ncigovcdode625.prod.acquia-sites.com/espanol/cancer/sobrellevar/sentimientos/test-and-test-article-glossification-sp

For PDQ Cancer Information Summary, I was seeing some console error on ODE 625 as well as on Prod PDQ Cancer Information Summary page ( Prod url : https://www.cancer.gov/types/breast/patient/breast-treatment-pdq). 
The discussion and screenshots about error are in the DP channel.

**Comment by blairlearn** [comment]
@bryanpizzillo the code changes look good to me, so I'm going to approve based on this.

However, I did notice that the list of PDQ-related files listed in #4028 is not the full set of PDQ-related files excluded in phpstan.neon.  It's not clear to me whether this is deliberate, or an oversight.

**Review by blairlearn — APPROVED** [review]
Approved for the files listed.  There are however additional PDQ-related files which were not listed in #4028 and will still cause phpstan errors.

**Pull request merged**
