### PR TITLE
Feature: Cancer Research Page

### LINKED ISSUE #162: Create Cancer Research Page (Mix of navigational and content pages)
**User Story:**
- As a content author I would like to create a [Cancer Research page](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Research-Page) on cancer.gov.  See [Form Display Order](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Research-Page#form-display-order)

**Acceptance Criteria:**

- I am required to enter the following common fields:
    * [Site Section](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Vocabularies-Site-Sections)
    * [Page Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#title-fields)
    * [Short Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Short-Title)
    * [Meta Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Meta-Description)
    * [Posted Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Updated Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Reviewed Date](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Search Engine Restrictions](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Search-Engine-Restrictions)

- I have the option to enter the following common fields:
    * [Card Title](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Card-Title)
    * [Browser Title](#Browser-Title)
    * [List Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#List-Description)
    * [Feature Card Description](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Feature-Card-Description)
    * [Pretty URL](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Pretty-URL)
    * [Date Display Mode](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Content-Dates)
    * [Body](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Body)
    * [Lead Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Lead-Image)
    * [Promotional Image](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#Promotional-Image)

- I have the option to enter the following local fields:
   * [Selected Research Pages](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Research-Page#selected-research-pages)
     * Note that the most recent DATE of the selected item should display in between the item title and description 

 - [Issue to Discuss](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Cancer-Research-Page#to-discussverify) – Whether to remove the following fields:
   * Public Use Text
   * Syndicate
   * Syndication Keywords

[Example of Cancer Research Page](https://www.cancer.gov/types/cervical/research)

**Tasks/Subtasks:**
- [ ] Add workflow transitions for Cancer Research page content type 
- [ ] Add content author and content reviewer permissions for Cancer Research page content type  
- [ ] Create Local fields
- [ ] Attach all fields

### LINKED ISSUE #1456: Cancer Research List Page - Front End Styling
We need to apply front-end styling to the cancer research list page content type.

Example List Page:
https://www.cancer.gov/types/liver/research

### PR DESCRIPTION
**Pull request by BrendanBeltzNIH**
Closes #162 , closes #1456

### CODE REVIEW

**Comment by arcepaul** [comment]
ODE is available at:
http://ncigovcdode84.prod.acquia-sites.com/

**Comment by VictoriaSunNIH** [comment]
@arcepaul - the body content is not appearing above the selected research link list when i put body into it.

See http://ncigovcdode84.prod.acquia-sites.com/types/testresearch

**Comment by VictoriaSunNIH** [comment]
Looks good!

**Comment by VictoriaSunNIH** [comment]
Lead image shouldn't work on this content type - can we remove it and only leave promotional image? @sarinapadilla

**Comment by lburack** [comment]
@sarinapadilla @arcepaul – Both @VictoriaSunNIH and I were able to successfully create a Cancer Research List page as expected, and have it display just like what you see on prod. Huzzah, this passes IA review!

**Comment by bryanpizzillo** [comment]
@arcepaul Can you get this up to date from develop so that I can just pull in the commits without squashing?

**Comment by bryanpizzillo** [comment]
I see the last update from develop added in a merge commit, so I am just going to squash this.

**Pull request merged**
