### PR TITLE
(#4246) Convert Favicons From Hardcoded to be Selectable

### LINKED ISSUE #4246: SPIKE: Convert Favicons From Hardcoded in the Page Template to be Selectable
**NOTE:** This is a spike/research story.

### Request Description
Favicons are currently hardcoded into the page template. This request is to change their implementation so that they can be set on a per-site basis with a default to the NCI luggage tag if the favicon is not overridden. Note: favicon are all of the icons - which includes apple icons and other unimportant ones.

### Technical Notes
- Should fix #3893 upon completion of this ticket. Whatever solution we pick shall /favicon.ico shall be set to the correct favicon in those cases
- There is a constraint the micro sites under www will need to have their favicon's set, but it will not be able to override the /favicon.ico (i.e. all microsites under the same root should have the exact same favicon)
  - **Requirement:** In our implementation we will set a theme folder that will be the root website. For pages under the root website, they will generate paths for the root website's files

### What is the Expected Change?
- Favicons will be set as the NCI luggage tag as default.
- Favicons will be able to be set on a per-site basis by overriding the default favicon

### What is the Current Functionality?
- Favicons are hardcoded in the page template

### Tasks

- [ ] @navsunka please investigate what modules set the "icons" and what options exist. First step is to find out what Drupal or a third-party module do, then verify against one of the sources listed below in the Notes section.

### What is the Updated Acceptance Criteria?
```gherkin
Scenario: An individual searching for a site on the Digital Platform sees the favicon of an NCI site in their Search Engine Results
  Given a user is on a search engine
    And they have searched for cancer.gov
  When the user is on the search engine results page
  Then the user will see the NCI favicon on the search result for cancer.gov
  When the user clicks the link of the page with the NCI favicon
  Then the tab that is opened of cancer.gov will show the NCI favicon
```

```gherkin
Scenario: An individual searching for a site on the Digital Platform sees a favicon for a site that does not use the NCI favicon in their Search Engine Results
  Given a user is on a search engine
    And they have searched for a site on the digital platform that does not use the NCI favicon
  When the user is on the search engine results page
  Then the user will see the custom favicon for the page that does not use the NCI favicon
  When the user clicks on the link of the page with the non-NCI favicon
  Then the tab that is opened will show the non-NCI favicon on the tab
```

```gherkin
Scenario: A site admin edits the favicon for a site within the Digital Platform
  Given the favicon is an editable field
    And the user is logged in as a site admin
  When the user chooses the NCI favicon
  Then the NCI favicon will appear in Search Engine results
    And the NCI favicon will appear on the tabs of pages opened with the NCI favicon selected
  When the user chooses a non-NCI favicon
  Then the selected non-NCI favicon will appear in Search Engine results
    And the selected non-NCI favicon will appear on the tabs of pages opened with the non-NCI favicon selected
  When the user does not make a selection of the favicon
  Then the favicon will default to the NCI favicon
    And the NCI favicon will appear in Search Engine results
    And the NCI favicon will appear in the tabs of pages without a favicon selection
```

### Notes
- There is not an easily accessible list of the specific icons/metatags from Googling, however they will be needed
- Some sources for information may be:
    - https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs
    - https://css-tricks.com/svg-favicons-and-all-the-fun-things-we-can-do-with-them/
- If Drupal has something built in, it is most likely out of date. If there is something built in/third party, we will most likely need to deal with what they do.
- Another thing found by Bryan:

> 
    <link rel="apple-touch-icon" sizes="180x180" href="/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/icons/favicons/apple-touch-icon.png?v=1" />
    <link rel="icon" type="image/png" href="/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/icons/favicons/favicon-32x32.png?v=1" sizes="32x32" />
    <link rel="icon" type="image/png" href="/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/icons/favicons/favicon-16x16.png?v=1" sizes="16x16" />
    <link rel="mask-icon" href="/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/icons/favicons/safari-pinned-tab.svg?v=1" color="#c0143c" />
    <link rel="shortcut icon" href="/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/icons/favicons/favicon.ico?v=1" />
<link rel="icon" href="/core/misc/favicon.ico" type="image/vnd.microsoft.icon" />
<link rel="icon" href="/core/misc/favicon.ico" type="image/vnd.microsoft.icon" />
<meta name="msapplication-config" content="/profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/icons/favicons/browserconfig.xml?v=1" />

### PR DESCRIPTION
**Pull request by navsunka**
Closes #4246

### CODE REVIEW

**Comment by blairlearn** [comment]
Summarizing various discussions:

- The `site_admin` role needs the permission to alter the favicon code.
- There should be a default value.
- The module needs to be enabled.
- There's an existing issue with cache not being cleared when the favicon HTML is updated
  - @navsunka please add a link to the Drupal issue.
  - This doesn't seem like a show-stopper since favicons aren't something we update very often.

**Comment by navsunka** [comment]
There are some caching issues when we add new favicons, below are existing issues related to those:
https://www.drupal.org/project/responsive_favicons/issues/3152918
https://www.drupal.org/project/responsive_favicons/issues/3197307

**Comment by blairlearn** [comment]
Two things

Something weird is going on here.  The icon files installed in `docroot/sites/default/files/favicons/` are not the ones from this pull request.

Here's the `apple-touch-icon.png`

image

Second, and less important, is there a way to suppress the "ad" the plugin adds to the page head?
`<meta name="favicon-generator" content="Drupal responsive_favicons + realfavicongenerator.net" />`

**Comment by blairlearn** [comment]
Putting the favicons into `docroot/sites/default/files` isn't going to work out because BLT overwrites our .gitignore with its own.  That path is used for uploaded content, so we shouldn't mess with it.

The reason the favicon HTML was stripped when the tags were pointed to their current location was because the module validates the paths (See the [_responsive_favicons_validate_tags](https://git.drupalcode.org/project/responsive_favicons/-/blob/8.x-1.x/responsive_favicons.module?ref_type=heads#L118) and [_responsive_favicons_normalise_path](https://git.drupalcode.org/project/responsive_favicons/-/blob/8.x-1.x/responsive_favicons.module?ref_type=heads#L184) functions).  This path can be adjusted by changing the `path` value in the settings.

**Comment by bryanpizzillo** [comment]
So what about the manifest.webmanifest file from both https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs and https://css-tricks.com/svg-favicons-and-all-the-fun-things-we-can-do-with-them/ ?
Those two links (from the ticket) outline the current best practices for favicons.

**Comment by navsunka** [comment]
Enabled responsive_favicons module. Configuration path (/admin/config/user-interface/responsive_favicons)

- I have added responsive_favicons.settings.yml file for setting a default favicon (current one) or we can upload a new favicon and add the HTML under favicon tags.
- - the path for the default favicon will be /profiles/custom/cgov_site/themes/custom/cgov/static/images/design-elements/icons/favicons where we have images already.
- - while we upload  the new favicon, the path will be /sites/default/files/favicons

_A web app manifest is a JSON file that tells the browser how your Progressive Web App (PWA) should behave when installed on the user's desktop or mobile device. manifest.webmanifest file is crucial for creating progressive web applications and enhancing the user experience of web applications across various devices and platforms. It provides metadata that helps browsers understand how to present and interact with your web app, leading to a more engaging and seamless user experience._

- We can either create our manifest file along with the other image files or create the same using https://realfavicongenerator.net/ (recommended by the responsive favicons module) and add it to the website.
- Description and creation of the manifest file can be done using this link: https://web.dev/articles/add-manifest

**Comment by andyvanavery31** [comment]
We need to get an svg created/designed for our favicon

**Comment by blairlearn** [comment]
This PR is replaced by #4337.

**Pull request closed without merging**
