### PR TITLE
Ticket/2347 blog category browser title

### LINKED ISSUE #2347: Blog Category Browser Titles
Browser Titles on blog category pages are pulling the browser title of the blog series itself. This is seen in the screenshot below and if you check the og:title in the source code on any of the blog category pages (ex: https://www.cancer.gov/news-events/cancer-currents-blog?topic=biology)

The browser title should be the same as the page title for these pages. This is important for SEO so all of these pages aren't being viewed as having the same exact title.

Screen Shot 2019-08-21 at 7 53 15 PM

### PR DESCRIPTION
**Pull request by kalidindir**
closes #2347

### CODE REVIEW

**Comment by kalidindir** [comment]
closes (#2382 )
closes (#2347 )

**Comment by VictoriaSunNIH** [comment]
@lburack  - I believe this is working as intended, I tested the following:
1. Looked at an existing English blog category page (both the browser title in Chrome, and the og:title) and they are appearing as the page title now
2. Tagged a spanish post with some blog categories to test the Spanish blog category page title (which works as expected)
3. Created a new blog category, in a new blog series, and then tagged a new post to that category to see the category page

All 3 of these scenarios worked as expected. I think this passes IA review, but let me know if I missed a scenario!

**Comment by lburack** [comment]
Looks like @VictoriaSunNIH got all of the scenarios. Marking this as passed IA review!

**Comment by bryanpizzillo** [comment]
@lburack I am going to commit this, but did you check the H1 tags? they changed as well. (I would argue for the better, and well @kalidindir would too since he fixed them.)

**Pull request merged**
