### PR TITLE
CTHP Content Type

### PR DESCRIPTION
**Pull request by sarinapadilla**
This PR contains the changes for the CTHP Content Type, excluding the Cancer Research Card.

### CODE REVIEW

**Comment by sarinapadilla** [comment]
Here's the ODE for testing: http://ncigovcdode54.prod.acquia-sites.com

**Comment by VictoriaSunNIH** [comment]
@lburack  - I've started this ticket to capture all the bugs: https://github.com/NCIOCPL/cgov-digital-platform/issues/1346

**Comment by VictoriaSunNIH** [comment]
@sarinapadilla - is a CTHP block card what I would need to use to create something like the Statistics card here? https://www.cancer.gov/types/leukemia/hp

**Comment by VictoriaSunNIH** [comment]
@sarinapadilla , @arcepaul - Let us know when these 3 outstanding tickets are ready for testing:
https://github.com/NCIOCPL/cgov-digital-platform/issues/1455
https://github.com/NCIOCPL/cgov-digital-platform/issues/1456
https://github.com/NCIOCPL/cgov-digital-platform/issues/1457

**Comment by arcepaul** [comment]
New ODE!
http://ncigovcdode93.prod.acquia-sites.com

**Comment by VictoriaSunNIH** [comment]
- Closes #1455 
- Closes #1449 
- Closes #1447 
- Closes #1346

**Pull request merged**
