### PR TITLE
(#2789) Updated popups to use new Glossary API

### LINKED ISSUE #2789: Update the Dictionary Service to point to new Glossary API
### Issue description
The new glossary API is live and the [JS Dictionary Service](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/themes/custom/cgov/src/libraries/dictionaryService/index.js) needs to consume the new API located at https://webapis.cancer.gov/glossary/v1/index.html. There are two front-end components using that service, the [dictionary popup](https://github.com/NCIOCPL/cgov-digital-platform/blob/8aaca637ac89352b3cd29a6ebb864402be107b5f/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/popups/popup_functions.js) and the [Site Wide Search](https://github.com/NCIOCPL/cgov-digital-platform/blob/8aaca637ac89352b3cd29a6ebb864402be107b5f/docroot/profiles/custom/cgov_site/themes/custom/cgov/cgov_common/src/libraries/bestBets/bestBets.js), which is going to be replaced soon-ish.

I think the easiest approach to take is to just update the service to point to the new API, transform the response to match the old, and then test. This way we don't have to mess with the UI components.

The Dictionary of Cancer Terms' name in the new API is `Cancer.gov`

> **ESTIMATE** NN

### Additional details / screenshot
- The ticket, #2663, should be done at the same time as this is part of the change.

### PR DESCRIPTION
**Pull request by bryanpizzillo**
- Implemented new glossary popup fetching and enhanced previous code.
   for extracting parameters for dictionary fetch.
- Made popup_functions backwards compatible with new glossary code.
- Added test content with multiple forms of dictionary links.
- Removed old dictionaryService as it has been replaced with the
   glossary-api-client-v1.
- Removed bestBets.js which referenced the dictionaryService. This
   code actually is not used in this stack. It is either in the legacy
   front-end codebase or the Site-wide search results app.
- Added in Regenerator support for babel via transform-runtime plugin.
   This is in order to support async/await calls in the glossary.

Closes #2789

### CODE REVIEW

**Comment by bryanpizzillo** [comment]
ODE: ncigovcdode349.prod.acquia-sites.com

**Comment by arcepaul** [comment]
@VictoriaSunNIH @lburack 
I'm gonna need your help on this one.  Do you have a list of where these popups occur so that I'm not missing anywhere?  The code bit is good to go but I just needed to do a visual check.

**Comment by bryanpizzillo** [comment]
English test links: http://ncigovcdode349.prod.acquia-sites.com/test/dictionary-link-test
Spanish test links: http://ncigovcdode349.prod.acquia-sites.com/espanol/test-es/dictionary-link-test

**Comment by VictoriaSunNIH** [comment]
This is good to go.

**Pull request merged**
