### PR TITLE
(#2845)  Add AP 'share this page' translation 

### LINKED ISSUE #2845: Update "Share this Page" Spanish translation
### Issue description
Spanish translation for "Share this Page" is missing

> **ESTIMATE** 

### What's the expected change?
- It should say "Compartir esta página"

### What's the current functionality?
- It says "Share this Page"

### What's the updated acceptance criteria?
```gherkin
Scenario: User views the AP Landing Page in Spanish
  Given language is set to "ES” 
    And the browser is 768 or less
  Then "Share this Page" should display as "Compartir esta página"
```

### Additional details / screenshot
-

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

### PR DESCRIPTION
**Pull request by adriancofie**
ODE: http://ncigovcdode386.prod.acquia-sites.com/
Closes #2845

### CODE REVIEW

**Comment by blilianyu** [comment]
Looks great to us!

**Comment by mworrest** [comment]
When creating a special report in Spanish from scratch (not just translating and existing English page) the share language is not translated. http://ncigovcdode387.prod.acquia-sites.com/espanol/node/906/revisions/1991/view
Screen Shot 2020-09-10 at 2 40 39 PM

**Review by arcepaul — APPROVED** [review]

**Review by bryanpizzillo — CHANGES_REQUESTED** [review]
The translations should go into https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/translations/cgov_site.es.po

`docroot/translations/drupal-8.7.x.es.po` is actually the Drupal core translations file.

**Comment by bryanpizzillo** [comment]
@adriancofie can you rebase this please?

**Pull request merged**
